"""
japan_tickers.py — Japanese TSE/JPX ticker search for EquityBot.

Strategy:
  1. Try to load from local cache (data/japan_tickers.json, 7-day TTL).
  2. If cache is missing/stale, fetch full TSE symbol list from EODHD
     /api/exchange-symbol-list endpoint — returns ~3 800 active listings.
  3. While EODHD fetch is running (or if it fails) fall back to the
     built-in seed list (~1 650 TOPIX constituents).

Search is by ticker code (numeric part) OR company name (partial, case-insensitive).
Returns Yahoo Finance format tickers: {CODE}.T  e.g. "7203.T" for Toyota.
"""
from __future__ import annotations

import json
import logging
import os
import time
from pathlib import Path
from typing import List, Dict, Optional

logger = logging.getLogger(__name__)

_HERE      = Path(__file__).parent
_CACHE     = _HERE.parent / "data" / "japan_tickers.json"
_CACHE_TTL = 7 * 24 * 3600        # 1 week in seconds

# ── Seed list — full TOPIX constituents (instant fallback, ~1 650 companies) ──
# Format: [code_without_suffix, name, sector]
_SEED: List[List[str]] = [
    ["1301", "KYOKUYO CO.,LTD.", "Consumer Defensive"],
    ["1332", "Nissui Corporation", "Consumer Defensive"],
    ["1333", "Umios Corporation", "Consumer Defensive"],
    ["1375", "YUKIGUNI FACTORY CO.,LTD.", "Consumer Defensive"],
    ["1376", "KANEKO SEEDS CO.,LTD.", "Consumer Defensive"],
    ["1377", "SAKATA SEED CORPORATION", "Consumer Defensive"],
    ["1379", "HOKUTO CORPORATION", "Consumer Defensive"],
    ["1414", "SHO-BOND Holdings Co.,Ltd.", "Industrials"],
    ["1417", "MIRAIT ONE Corporation", "Industrials"],
    ["1419", "Tama Home Co.,Ltd.", "Industrials"],
    ["1435", "robot home Inc.", "Real Estate"],
    ["1514", "Sumiseki Holdings,Inc.", "Energy"],
    ["1515", "Nittetsu Mining Co.,Ltd.", "Energy"],
    ["1518", "MITSUI MATSUSHIMA HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["1605", "INPEX CORPORATION", "Energy"],
    ["1662", "Japan Petroleum Exploration Co.,Ltd.", "Energy"],
    ["1663", "K&O Energy Group Inc.", "Energy"],
    ["167A", "Ryoyo Ryosan Holdings,Inc.", "Consumer Cyclical"],
    ["1716", "DAI-ICHI CUTTER KOGYO K.K.", "Industrials"],
    ["1719", "HAZAMA ANDO CORPORATION", "Industrials"],
    ["1720", "TOKYU CONSTRUCTION CO., LTD.", "Industrials"],
    ["1721", "COMSYS Holdings Corporation", "Industrials"],
    ["1726", "Br.Holdings Corporation", "Industrials"],
    ["1762", "TAKAMATSU CONSTRUCTION GROUP CO.,LTD.", "Industrials"],
    ["1766", "TOKEN CORPORATION", "Industrials"],
    ["1780", "YAMAURA CORPORATION", "Industrials"],
    ["1786", "Oriental Shiraishi Corporation", "Industrials"],
    ["1801", "TAISEI CORPORATION", "Industrials"],
    ["1802", "OBAYASHI CORPORATION", "Industrials"],
    ["1803", "SHIMIZU CORPORATION", "Industrials"],
    ["1808", "HASEKO Corporation", "Industrials"],
    ["1810", "MATSUI CONSTRUCTION CO.,LTD.", "Industrials"],
    ["1812", "KAJIMA CORPORATION", "Industrials"],
    ["1813", "Fudo Tetra Corporation", "Industrials"],
    ["1815", "TEKKEN CORPORATION", "Industrials"],
    ["1820", "Nishimatsu Construction Co.,Ltd.", "Industrials"],
    ["1822", "DAIHO CORPORATION", "Industrials"],
    ["1833", "OKUMURA CORPORATION", "Industrials"],
    ["1835", "TOTETSU KOGYO CO.,LTD.", "Industrials"],
    ["1852", "ASANUMA CORPORATION", "Industrials"],
    ["1860", "TODA CORPORATION", "Industrials"],
    ["1861", "Kumagai Gumi Co.,Ltd.", "Industrials"],
    ["1870", "YAHAGI CONSTRUCTION CO.,LTD.", "Industrials"],
    ["1871", "PS Construction Co.,Ltd.", "Industrials"],
    ["1873", "NIHON HOUSE HOLDINGS CO.,LTD.", "Industrials"],
    ["1878", "DAITO TRUST CONSTRUCTION CO.,LTD.", "Real Estate"],
    ["1879", "SHINNIHON CORPORATION", "Industrials"],
    ["1882", "TOA ROAD CORPORATION", "Industrials"],
    ["1885", "TOA CORPORATION", "Industrials"],
    ["1887", "JDC CORPORATION", "Industrials"],
    ["1888", "WAKACHIKU CONSTRUCTION CO.,LTD.", "Industrials"],
    ["1893", "PENTA-OCEAN CONSTRUCTION CO.,LTD.", "Industrials"],
    ["1898", "SEIKITOKYU KOGYO CO.,LTD.", "Industrials"],
    ["1899", "FUKUDA CORPORATION", "Industrials"],
    ["1911", "Sumitomo Forestry Co.,Ltd.", "Industrials"],
    ["1925", "DAIWA HOUSE INDUSTRY CO.,LTD.", "Industrials"],
    ["1926", "RAITO KOGYO CO.,LTD.", "Industrials"],
    ["1928", "Sekisui House,Ltd.", "Industrials"],
    ["1929", "NITTOC CONSTRUCTION CO.,LTD.", "Industrials"],
    ["1930", "HOKURIKU ELECTRICAL CONSTRUCTION CO.,LTD.", "Industrials"],
    ["1934", "YURTEC CORPORATION", "Industrials"],
    ["1938", "NIPPON RIETEC CO.,LTD.", "Industrials"],
    ["1939", "YONDENKO CORPORATION", "Industrials"],
    ["1941", "CHUDENKO CORPORATION", "Industrials"],
    ["1942", "KANDENKO CO.,LTD.", "Industrials"],
    ["1944", "KINDEN CORPORATION", "Industrials"],
    ["1945", "TOKYO ENERGY & SYSTEMS INC.", "Industrials"],
    ["1946", "TOENEC CORPORATION", "Industrials"],
    ["1950", "NIPPON DENSETSU KOGYO CO.,LTD.", "Industrials"],
    ["1951", "EXEO Group,Inc.", "Industrials"],
    ["1952", "Shin Nippon Air Technologies Co.,Ltd.", "Industrials"],
    ["1959", "KRAFTIA CORPORATION", "Industrials"],
    ["1961", "SANKI ENGINEERING CO.,LTD.", "Industrials"],
    ["1963", "JGC HOLDINGS CORPORATION", "Industrials"],
    ["1964", "Chugai Ro Co.,Ltd.", "Industrials"],
    ["1968", "TAIHEI DENGYO KAISHA,LTD.", "Industrials"],
    ["1969", "Takasago Thermal Engineering Co.,Ltd.", "Industrials"],
    ["1975", "ASAHI KOGYOSHA CO.,LTD.", "Industrials"],
    ["1976", "MEISEI INDUSTRIAL Co.,Ltd.", "Industrials"],
    ["1979", "Taikisha Ltd.", "Industrials"],
    ["1980", "DAI-DAN CO.,LTD.", "Industrials"],
    ["1982", "Hibiya Engineering,Ltd.", "Industrials"],
    ["2001", "NIPPN CORPORATION", "Consumer Defensive"],
    ["2002", "NISSHIN SEIFUN GROUP INC.", "Consumer Defensive"],
    ["2003", "NITTO FUJI FLOUR MILLING CO.,LTD.", "Consumer Defensive"],
    ["2004", "Showa Sangyo Co.,Ltd.", "Consumer Defensive"],
    ["2053", "CHUBU SHIRYO CO.,LTD.", "Consumer Defensive"],
    ["2060", "FEED ONE CO.,LTD.", "Consumer Defensive"],
    ["2108", "Nippon Beet Sugar Manufacturing Co.,Ltd.", "Consumer Defensive"],
    ["2109", "Mitsui DM Sugar Co.,Ltd.", "Consumer Defensive"],
    ["2117", "WELLNEO SUGAR Co.,Ltd.", "Consumer Defensive"],
    ["2120", "LIFULL Co.,Ltd.", "Industrials"],
    ["2121", "MIXI,Inc.", "Technology"],
    ["2124", "JAC Recruitment Co.,Ltd.", "Industrials"],
    ["2127", "Nihon M&A Center Holdings Inc.", "Industrials"],
    ["212A", "FIT EASY Inc.", "Industrials"],
    ["2130", "Members Co.,Ltd.", "Industrials"],
    ["2146", "UT Group Co.,Ltd.", "Industrials"],
    ["2148", "ITmedia Inc.", "Industrials"],
    ["2153", "E�EJ Holdings Inc.", "Industrials"],
    ["2154", "Open Up Group Inc.", "Industrials"],
    ["2157", "KOSHIDAKA HOLDINGS Co.,LTD.", "Industrials"],
    ["2168", "Pasona Group Inc.", "Industrials"],
    ["2170", "Link and Motivation Inc.", "Industrials"],
    ["2175", "SMS CO.,LTD.", "Industrials"],
    ["2181", "PERSOL HOLDINGS CO.,LTD.", "Industrials"],
    ["2193", "Cookpad Inc.", "Industrials"],
    ["2201", "Morinaga & Co.,Ltd.", "Consumer Defensive"],
    ["2204", "NAKAMURAYA CO.,LTD.", "Consumer Defensive"],
    ["2206", "Ezaki Glico Co.,Ltd.", "Consumer Defensive"],
    ["2207", "MEITO CO.,LTD.", "Consumer Defensive"],
    ["2209", "IMURAYA GROUP CO.,LTD.", "Consumer Defensive"],
    ["2211", "Fujiya Co.,Ltd.", "Consumer Defensive"],
    ["2212", "YAMAZAKI BAKING CO.,LTD.", "Consumer Defensive"],
    ["2217", "Morozoff Limited", "Consumer Defensive"],
    ["2220", "KAMEDA SEIKA CO.,LTD.", "Consumer Defensive"],
    ["2222", "Kotobuki Spirits Co.,Ltd.", "Consumer Defensive"],
    ["2229", "CALBEE,Inc.", "Consumer Defensive"],
    ["2264", "MORINAGA MILK INDUSTRY CO.,LTD.", "Consumer Defensive"],
    ["2266", "ROKKO BUTTER CO.,LTD.", "Consumer Defensive"],
    ["2267", "YAKULT HONSHA CO.,LTD.", "Consumer Defensive"],
    ["2269", "Meiji Holdings Co.,Ltd.", "Consumer Defensive"],
    ["2270", "MEGMILK SNOW BRAND Co.,Ltd.", "Consumer Defensive"],
    ["2281", "Prima Meat Packers,Ltd.", "Consumer Defensive"],
    ["2282", "NH Foods Ltd.", "Consumer Defensive"],
    ["2288", "MARUDAI FOOD CO.,LTD.", "Consumer Defensive"],
    ["2292", "S Foods Inc.", "Consumer Defensive"],
    ["2294", "Kakiyasu Honten Co.,Ltd.", "Consumer Defensive"],
    ["2296", "ITOHAM YONEKYU HOLDINGS INC.", "Consumer Defensive"],
    ["2301", "GAKUJO CO.,Ltd.", "Industrials"],
    ["2305", "STUDIO ALICE Co.,Ltd.", "Industrials"],
    ["2307", "CROSS CAT CO.,LTD.", "Technology"],
    ["2317", "Systena Corporation", "Technology"],
    ["2325", "NJS Co.,Ltd.", "Industrials"],
    ["2326", "Digital Arts Inc.", "Technology"],
    ["2327", "NS Solutions Corporation", "Technology"],
    ["2331", "ALSOK CO.,LTD.", "Industrials"],
    ["2335", "CUBE SYSTEM INC.", "Technology"],
    ["2337", "Ichigo Inc.", "Real Estate"],
    ["2353", "NIPPON PARKING DEVELOPMENT Co.,Ltd.", "Real Estate"],
    ["2359", "CORE CORPORATION", "Technology"],
    ["2371", "Kakaku.com,Inc.", "Industrials"],
    ["2378", "RENAISSANCE,INCORPORATED", "Industrials"],
    ["2379", "dip Corporation", "Industrials"],
    ["2384", "SBS Holdings,Inc.", "Industrials"],
    ["2395", "SHIN NIPPON BIOMEDICAL LABORATORIES,LTD.", "Industrials"],
    ["2413", "M3,Inc.", "Industrials"],
    ["2429", "WORLD HOLDINGS CO.,LTD.", "Industrials"],
    ["2432", "DeNA Co.,Ltd.", "Technology"],
    ["2433", "HAKUHODO DY HOLDINGS INCORPORATED", "Industrials"],
    ["2440", "Gurunavi,Inc.", "Industrials"],
    ["2445", "Takamiya Co.,Ltd.", "Industrials"],
    ["2461", "FAN Communications,Inc.", "Industrials"],
    ["2462", "LIKE,Inc.", "Industrials"],
    ["2471", "S-Pool,Inc.", "Industrials"],
    ["2475", "WDB HOLDINGS CO.,LTD.", "Industrials"],
    ["2477", "Temairazu,Inc.", "Technology"],
    ["2489", "Adways Inc.", "Industrials"],
    ["2491", "ValueCommerce Co.,Ltd.", "Industrials"],
    ["2492", "Infomart Corporation", "Industrials"],
    ["2501", "SAPPORO HOLDINGS LIMITED", "Consumer Defensive"],
    ["2502", "Asahi Group Holdings,Ltd.", "Consumer Defensive"],
    ["2503", "Kirin Holdings Company,Limited", "Consumer Defensive"],
    ["250A", "Shimadaya Corporation", "Consumer Defensive"],
    ["2531", "TAKARA HOLDINGS INC.", "Consumer Defensive"],
    ["2533", "Oenon Holdings,Inc.", "Consumer Defensive"],
    ["2540", "YOMEISHU SEIZO CO.,LTD.", "Consumer Defensive"],
    ["256A", "TOBISHIMA HOLDINGS Inc.", "Industrials"],
    ["2579", "Coca-Cola Bottlers Japan Holdings Inc.", "Consumer Defensive"],
    ["2585", "LIFEDRINK COMPANY,INC.", "Consumer Defensive"],
    ["2587", "Suntory Beverage & Food Limited", "Consumer Defensive"],
    ["2590", "DyDo GROUP HOLDINGS,INC.", "Consumer Defensive"],
    ["2593", "ITO EN,LTD.", "Consumer Defensive"],
    ["2594", "KEY COFFEE INC", "Consumer Defensive"],
    ["2602", "The Nisshin OilliO Group,Ltd.", "Consumer Defensive"],
    ["2607", "FUJI OIL CO.,LTD.", "Consumer Defensive"],
    ["2613", "J-OIL MILLS, INC.", "Consumer Defensive"],
    ["262A", "INTERMESTIC INC.", "Consumer Cyclical"],
    ["2659", "SAN-A CO.,LTD.", "Consumer Cyclical"],
    ["2664", "CAWACHI LIMITED", "Consumer Cyclical"],
    ["2670", "ABC-MART,INC.", "Consumer Cyclical"],
    ["2674", "HARD OFF CORPORATION Co.,Ltd.", "Consumer Cyclical"],
    ["2676", "TAKACHIHO KOHEKI CO.,LTD.", "Consumer Cyclical"],
    ["2678", "ASKUL Corporation", "Consumer Cyclical"],
    ["2681", "GEO HOLDINGS CORPORATION", "Consumer Cyclical"],
    ["2685", "and ST HD Co.,Ltd.", "Consumer Cyclical"],
    ["268A", "Rigaku Holdings Corporation", "Technology"],
    ["2692", "ITOCHU-SHOKUHIN Co.,Ltd.", "Consumer Cyclical"],
    ["2695", "Kura Sushi,Inc.", "Consumer Cyclical"],
    ["2698", "CAN DO CO.,LTD.", "Consumer Cyclical"],
    ["2726", "PAL GROUP Holdings CO.,LTD", "Consumer Cyclical"],
    ["2730", "EDION Corporation", "Consumer Cyclical"],
    ["2733", "ARATA CORPORATION", "Consumer Cyclical"],
    ["2734", "SALA CORPORATION", "Consumer Cyclical"],
    ["2737", "TOMEN DEVICES CORPORATION", "Consumer Cyclical"],
    ["2742", "HALOWS CO.,LTD.", "Consumer Cyclical"],
    ["2749", "JP-HOLDINGS,INC.", "Industrials"],
    ["2752", "FUJIO FOOD GROUP INC.", "Consumer Cyclical"],
    ["2753", "AMIYAKI TEI CO.,LTD.", "Consumer Cyclical"],
    ["2760", "TOKYO ELECTRON DEVICE LIMITED", "Consumer Cyclical"],
    ["2767", "TSUBURAYA FIELDS HOLDINGS INC.", "Consumer Cyclical"],
    ["2768", "Sojitz Corporation", "Consumer Cyclical"],
    ["2784", "Alfresa Holdings Corporation", "Consumer Cyclical"],
    ["2791", "DAIKOKUTENBUSSAN CO.,LTD.", "Consumer Cyclical"],
    ["2792", "HONEYS HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["2801", "KIKKOMAN CORPORATION", "Consumer Defensive"],
    ["2802", "Ajinomoto Co.,Inc.", "Consumer Defensive"],
    ["2804", "BULL-DOG SAUCE CO.,LTD.", "Consumer Defensive"],
    ["2809", "Kewpie Corporation", "Consumer Defensive"],
    ["2810", "House Foods Group Inc.", "Consumer Defensive"],
    ["2811", "KAGOME CO.,LTD.", "Consumer Defensive"],
    ["2815", "ARIAKE JAPAN Co.,Ltd.", "Consumer Defensive"],
    ["2819", "EBARA Foods Industry,Inc.", "Consumer Defensive"],
    ["285A", "Kioxia Holdings Corporation", "Technology"],
    ["2871", "NICHIREI CORPORATION", "Consumer Defensive"],
    ["2874", "YOKOREI CO.,LTD.", "Consumer Cyclical"],
    ["2875", "TOYO SUISAN KAISHA,LTD.", "Consumer Defensive"],
    ["2882", "EAT&HOLDINGS Co.,Ltd", "Consumer Defensive"],
    ["2884", "Yoshimura Food Holdings K.K.", "Consumer Defensive"],
    ["2897", "NISSIN FOODS HOLDINGS CO.,LTD.", "Consumer Defensive"],
    ["2908", "FUJICCO CO.,LTD.", "Consumer Defensive"],
    ["2910", "ROCK FIELD CO.,LTD.", "Consumer Defensive"],
    ["2914", "JAPAN TOBACCO INC.", "Consumer Defensive"],
    ["2915", "KENKO Mayonnaise Co.,Ltd.", "Consumer Defensive"],
    ["2918", "WARABEYA NICHIYO HOLDINGS CO.,LTD.", "Consumer Defensive"],
    ["2922", "NATORI CO.,LTD.", "Consumer Defensive"],
    ["2929", "Pharma Foods International Co.,Ltd.", "Consumer Defensive"],
    ["2930", "Kitanotatsujin Corporation", "Basic Materials"],
    ["2931", "Euglena Co.,Ltd.", "Consumer Defensive"],
    ["2933", "KIBUN FOODS INC.", "Consumer Defensive"],
    ["2935", "PICKLES HOLDINGS CO.,LTD.", "Consumer Defensive"],
    ["2975", "Star Mica Holdings Co.,Ltd.", "Real Estate"],
    ["2980", "SRE Holdings Corporation", "Real Estate"],
    ["3001", "Katakura Industries Co.,Ltd.", "Consumer Cyclical"],
    ["3002", "GUNZE LIMITED", "Consumer Cyclical"],
    ["3003", "Hulic Co.,Ltd.", "Real Estate"],
    ["3023", "Rasa Corporation", "Consumer Cyclical"],
    ["3028", "Alpen Co.,Ltd.", "Consumer Cyclical"],
    ["3031", "RACCOON HOLDINGS,Inc.", "Technology"],
    ["3034", "Qol Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["3036", "ALCONIX CORPORATION", "Consumer Cyclical"],
    ["3038", "KOBE BUSSAN CO.,LTD.", "Consumer Cyclical"],
    ["3040", "SOLITON SYSTEMS K.K.", "Technology"],
    ["3046", "JINS HOLDINGS Inc.", "Consumer Cyclical"],
    ["3048", "BIC CAMERA INC.", "Consumer Cyclical"],
    ["3050", "DCM Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["3053", "PEPPER FOOD SERVICE CO.,LTD.", "Consumer Cyclical"],
    ["3064", "MonotaRO Co.,Ltd.", "Consumer Cyclical"],
    ["3076", "Ai Holdings Corporation", "Consumer Cyclical"],
    ["3086", "J.FRONT RETAILING Co.,Ltd.", "Consumer Cyclical"],
    ["3087", "DOUTOR�ENICHIRES Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["3088", "MatsukiyoCocokara & Co.", "Consumer Cyclical"],
    ["3091", "BRONCO BILLY Co.,LTD.", "Consumer Cyclical"],
    ["3092", "ZOZO,Inc.", "Consumer Cyclical"],
    ["3093", "Treasure Factory Co.,LTD.", "Consumer Cyclical"],
    ["3097", "The Monogatari Corporation", "Consumer Cyclical"],
    ["3099", "Isetan Mitsukoshi Holdings Ltd.", "Consumer Cyclical"],
    ["3101", "TOYOBO CO.,LTD.", "Basic Materials"],
    ["3103", "UNITIKA LTD.", "Consumer Cyclical"],
    ["3104", "Fujibo Holdings,Inc.", "Consumer Cyclical"],
    ["3105", "Nisshinbo Holdings Inc.", "Technology"],
    ["3106", "KURABO INDUSTRIES LTD.", "Consumer Cyclical"],
    ["3107", "Daiwabo Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["3109", "SHIKIBO LTD.", "Consumer Cyclical"],
    ["3110", "NITTO BOSEKI CO.,LTD.", "Basic Materials"],
    ["3116", "TOYOTA BOSHOKU CORPORATION", "Industrials"],
    ["3132", "MACNICA HOLDINGS,INC.", "Consumer Cyclical"],
    ["3134", "Hamee Corp.", "Consumer Cyclical"],
    ["3139", "Lacto Japan Co.,Ltd.", "Consumer Cyclical"],
    ["3148", "CREATE SD HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["3150", "grems,Inc.", "Utilities"],
    ["3151", "VITAL KSK HOLDINGS,INC.", "Consumer Cyclical"],
    ["3153", "Yashima Denki Co.,Ltd.", "Consumer Cyclical"],
    ["3154", "MEDIUS HOLDINGS Co.,Ltd.", "Consumer Cyclical"],
    ["3156", "Restar Corporation", "Consumer Cyclical"],
    ["3167", "TOKAI Holdings Corporation", "Consumer Cyclical"],
    ["3176", "Sanyo Trading Co.,Ltd.", "Consumer Cyclical"],
    ["3179", "Syuppin Co.,Ltd.", "Consumer Cyclical"],
    ["3180", "BEAUTY GARAGE Inc.", "Consumer Cyclical"],
    ["3182", "Oisix ra daichi Inc.", "Consumer Cyclical"],
    ["3183", "WIN-Partners Co.,Ltd.", "Consumer Cyclical"],
    ["3186", "NEXTAGE Co.,Ltd.", "Consumer Cyclical"],
    ["3191", "JOYFUL HONDA CO.,LTD.", "Consumer Cyclical"],
    ["3193", "Eternal Hospitality Group Co.,Ltd.", "Consumer Cyclical"],
    ["3196", "HOTLAND HOLDINGS Co.,Ltd.", "Consumer Cyclical"],
    ["3197", "SKYLARK HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["3198", "SFP Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["3199", "Watahan & Co.,Ltd.", "Consumer Cyclical"],
    ["3201", "THE JAPAN WOOL TEXTILE CO.,LTD.", "Consumer Cyclical"],
    ["3221", "Yossix Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["3222", "United Super Markets Holdings Inc.", "Consumer Cyclical"],
    ["3231", "Nomura Real Estate Holdings,Inc.", "Real Estate"],
    ["3232", "Mie Kotsu Group Holdings,Inc.", "Real Estate"],
    ["3245", "DEAR LIFE CO.,LTD.", "Real Estate"],
    ["3252", "JINUSHI Co.,Ltd.", "Real Estate"],
    ["3267", "Phil Company,Inc.", "Industrials"],
    ["3276", "Japan Property Management Center Co.,Ltd.", "Real Estate"],
    ["3284", "Hoosiers Holdings Co.,Ltd.", "Real Estate"],
    ["3288", "Open House Group Co.,Ltd.", "Real Estate"],
    ["3289", "Tokyu Fudosan Holdings Corporation", "Real Estate"],
    ["3291", "Iida Group Holdings Co.,Ltd.", "Real Estate"],
    ["3302", "TEIKOKU SEN-I Co.,Ltd.", "Consumer Cyclical"],
    ["3315", "NIPPON COKE & ENGINEERING COMPANY,LIMITED", "Energy"],
    ["3333", "ASAHI CO.,LTD.", "Consumer Cyclical"],
    ["3349", "COSMOS Pharmaceutical Corporation", "Consumer Cyclical"],
    ["3360", "SHIP HEALTHCARE HOLDINGS,INC.", "Consumer Cyclical"],
    ["3371", "SOFTCREATE HOLDINGS CORP.", "Technology"],
    ["3382", "Seven & i Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["3387", "create restaurants holdings inc.", "Consumer Cyclical"],
    ["3388", "MEIJI ELECTRIC INDUSTRIES CO.,LTD.", "Consumer Cyclical"],
    ["3391", "TSURUHA HOLDINGS INC.", "Consumer Cyclical"],
    ["3395", "Saint Marc Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["3397", "TORIDOLL Holdings Corporation", "Consumer Cyclical"],
    ["3401", "TEIJIN LIMITED", "Consumer Cyclical"],
    ["3402", "TORAY INDUSTRIES,INC.", "Consumer Cyclical"],
    ["3405", "KURARAY CO.,LTD.", "Basic Materials"],
    ["3407", "ASAHI KASEI CORPORATION", "Basic Materials"],
    ["3415", "TOKYO BASE Co.,Ltd.", "Consumer Cyclical"],
    ["3421", "INABA SEISAKUSHO Co.,Ltd.", "Industrials"],
    ["3431", "MIYAJI ENGINEERING GROUP,INC.", "Industrials"],
    ["3433", "TOCALO Co.,Ltd.", "Industrials"],
    ["3436", "SUMCO CORPORATION", "Industrials"],
    ["3443", "KAWADA TECHNOLOGIES,INC.", "Industrials"],
    ["3445", "RS Technologies Co.,Ltd.", "Industrials"],
    ["3457", "&Do Holdings Co.,Ltd.", "Real Estate"],
    ["3465", "KI-STAR REAL ESTATE CO.,LTD", "Real Estate"],
    ["3475", "Good Com Asset Co.,Ltd.", "Real Estate"],
    ["3480", "J.S.B.Co.,Ltd.", "Real Estate"],
    ["3482", "Loadstar Capital K.K.", "Real Estate"],
    ["3496", "AZOOM CO.,LTD", "Real Estate"],
    ["3498", "Kasumigaseki Capital Co.,Ltd.", "Real Estate"],
    ["3539", "JM HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["3543", "KOMEDA Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["3546", "Alleanza Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["3547", "UNISIA HOLDINGS CO.", "Consumer Cyclical"],
    ["3548", "BAROQUE JAPAN LIMITED", "Consumer Cyclical"],
    ["3549", "KUSURI NO AOKI HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["3561", "CHIKARANOMOTO HOLDINGS Co.,Ltd.", "Consumer Cyclical"],
    ["3563", "FOOD & LIFE COMPANIES LTD.", "Consumer Cyclical"],
    ["3565", "Ascentech K.K.", "Consumer Cyclical"],
    ["3569", "SEIREN CO.,LTD.", "Consumer Cyclical"],
    ["3580", "KOMATSU MATERE Co.,Ltd.", "Consumer Cyclical"],
    ["3591", "WACOAL HOLDINGS CORP.", "Consumer Cyclical"],
    ["3593", "HOGY MEDICAL CO.,LTD.", "Consumer Cyclical"],
    ["3608", "TSI HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["3612", "WORLD CO.,LTD.", "Consumer Cyclical"],
    ["3626", "TIS Inc.", "Technology"],
    ["3632", "GREE Holdings,Inc.", "Technology"],
    ["3633", "GMO Pepabo,Inc.", "Technology"],
    ["3635", "KOEI TECMO HOLDINGS CO.,LTD.", "Technology"],
    ["3636", "Mitsubishi Research Institute,Inc.", "Technology"],
    ["3649", "FINDEX Inc.", "Technology"],
    ["3656", "KLab Inc.", "Technology"],
    ["3657", "Pole To Win Holdings,Inc.", "Technology"],
    ["3659", "NEXON Co.,Ltd.", "Technology"],
    ["3660", "istyle Inc.", "Technology"],
    ["3661", "m-up holdings,Inc.", "Technology"],
    ["3662", "Ateam Holdings Co.,Ltd.", "Technology"],
    ["3663", "CELSYS,Inc.", "Technology"],
    ["3665", "Enigmo Inc.", "Technology"],
    ["3668", "COLOPL,Inc.", "Technology"],
    ["3673", "Broadleaf Co.,Ltd.", "Technology"],
    ["3676", "DIGITAL HEARTS HOLDINGS Co.,Ltd.", "Technology"],
    ["3678", "MEDIA DO Co.,Ltd.", "Technology"],
    ["3679", "ZIGExN Co.,Ltd.", "Technology"],
    ["3681", "V-cube,Inc.", "Technology"],
    ["3687", "Fixstars Corporation", "Technology"],
    ["368A", "Kitazato Corporation", "Technology"],
    ["3694", "OPTiM CORPORATION", "Technology"],
    ["3696", "CERES INC.", "Technology"],
    ["3697", "SHIFT Inc.", "Technology"],
    ["3708", "Tokushu Tokai Paper Co.,Ltd.", "Basic Materials"],
    ["3741", "Systems Engineering Consultants Co.,LTD.", "Technology"],
    ["3762", "TECHMATRIX CORPORATION", "Technology"],
    ["3763", "Pro-Ship Incorporated", "Technology"],
    ["3765", "GungHo Online Entertainment,Inc.", "Technology"],
    ["3769", "GMO Payment Gateway,Inc.", "Technology"],
    ["3771", "SYSTEM RESEARCH CO.,LTD.", "Technology"],
    ["3774", "Internet Initiative Japan Inc.", "Technology"],
    ["3778", "SAKURA internet Inc.", "Technology"],
    ["3788", "GMO GlobalSign Holdings K.K.", "Technology"],
    ["3817", "SRA Holdings,Inc.", "Technology"],
    ["3834", "Asahi Net,Inc.", "Technology"],
    ["3835", "eBASE Co.,Ltd.", "Technology"],
    ["3836", "AVANT GROUP CORPORATION", "Technology"],
    ["3837", "Ad-Sol Nissin Corporation", "Technology"],
    ["3843", "FreeBit Co.,Ltd.", "Technology"],
    ["3844", "COMTURE CORPORATION", "Technology"],
    ["3853", "ASTERIA Corporation", "Technology"],
    ["3854", "I'LL INC", "Technology"],
    ["3861", "Oji Holdings Corporation", "Basic Materials"],
    ["3863", "Nippon Paper Industries Co.,Ltd.", "Basic Materials"],
    ["3865", "Hokuetsu Corporation", "Basic Materials"],
    ["3880", "Daio Paper Corporation", "Basic Materials"],
    ["3901", "MarkLines Co.,Ltd.", "Technology"],
    ["3903", "gumi Inc.", "Technology"],
    ["3915", "TerraSky Co.,Ltd", "Technology"],
    ["3916", "Digital Information Technologies Corporation", "Technology"],
    ["3921", "NEOJAPAN Inc.", "Technology"],
    ["3922", "PR TIMES Corporation", "Technology"],
    ["3923", "RAKUS Co.,Ltd.", "Technology"],
    ["3925", "Double Standard Inc.", "Technology"],
    ["3926", "Open Door Inc.", "Technology"],
    ["3932", "Akatsuki Inc.", "Technology"],
    ["3937", "Ubicom Holdings,Inc.", "Technology"],
    ["3939", "Kanamic Network Co.,LTD", "Technology"],
    ["3941", "Rengo Co.,Ltd.", "Basic Materials"],
    ["3946", "TOMOKU CO.,LTD.", "Basic Materials"],
    ["3950", "THE PACK CORPORATION", "Basic Materials"],
    ["3962", "CHANGE Holdings,Inc.", "Technology"],
    ["3964", "AUCNET INC.", "Technology"],
    ["3983", "ORO Co.,Ltd.", "Technology"],
    ["3984", "User Local,Inc.", "Technology"],
    ["3993", "PKSHA Technology Inc.", "Technology"],
    ["3994", "Money Forward,Inc.", "Technology"],
    ["4004", "Resonac Holdings Corporation", "Basic Materials"],
    ["4005", "SUMITOMO CHEMICAL COMPANY,LIMITED", "Basic Materials"],
    ["4008", "Sumitomo Seika Chemicals Company,Limited.", "Basic Materials"],
    ["4021", "Nissan Chemical Corporation", "Basic Materials"],
    ["4022", "Rasa Industries,Ltd.", "Basic Materials"],
    ["4023", "KUREHA CORPORATION", "Basic Materials"],
    ["4025", "TAKI CHEMICAL CO.,LTD.", "Basic Materials"],
    ["4027", "TAYCA CORPORATION", "Basic Materials"],
    ["4028", "ISHIHARA SANGYO KAISHA,LTD.", "Basic Materials"],
    ["4041", "Nippon Soda Co.,Ltd.", "Basic Materials"],
    ["4042", "TOSOH CORPORATION", "Basic Materials"],
    ["4043", "Tokuyama Corporation", "Basic Materials"],
    ["4044", "Central Glass Co.,Ltd.", "Basic Materials"],
    ["4045", "TOAGOSEI CO.,LTD.", "Basic Materials"],
    ["4046", "OSAKA SODA CO.,LTD.", "Basic Materials"],
    ["4047", "KANTO DENKA KOGYO CO.,LTD.", "Basic Materials"],
    ["4051", "GMO Financial Gate,Inc.", "Technology"],
    ["4053", "Sun* Inc.", "Technology"],
    ["4061", "Denka Company Limited", "Basic Materials"],
    ["4062", "IBIDEN CO.,LTD.", "Technology"],
    ["4063", "Shin-Etsu Chemical Co.,Ltd.", "Basic Materials"],
    ["4064", "Nippon Carbide Industries Company,Incorporated", "Basic Materials"],
    ["4071", "Plus Alpha Consulting Co.,LTD.", "Technology"],
    ["4072", "Densan System Holdings Co.,Ltd.", "Technology"],
    ["4078", "Sakai Chemical Industry Co.,Ltd.", "Basic Materials"],
    ["4082", "DAIICHI KIGENSO KAGAKU-KOGYO CO.,LTD", "Basic Materials"],
    ["4088", "AIR WATER INC.", "Basic Materials"],
    ["4091", "NIPPON SANSO HOLDINGS CORPORATION", "Basic Materials"],
    ["4092", "Nippon Chemical Industrial Co.,Ltd.", "Basic Materials"],
    ["4095", "NIHON PARKERIZING CO.,LTD.", "Basic Materials"],
    ["4097", "KOATSU GAS KOGYO CO.,LTD.", "Basic Materials"],
    ["4099", "SHIKOKU KASEI HOLDINGS CORPORATION", "Basic Materials"],
    ["409A", "ORION BREWERIES,LTD.", "Consumer Defensive"],
    ["4100", "TODA KOGYO CORP.", "Basic Materials"],
    ["4109", "STELLA CHEMIFA CORPORATION", "Basic Materials"],
    ["4112", "Hodogaya Chemical Co.,Ltd.", "Basic Materials"],
    ["4114", "NIPPON SHOKUBAI CO.,LTD.", "Basic Materials"],
    ["4116", "Dainichiseika Color & Chemicals Mfg.Co.,Ltd.", "Basic Materials"],
    ["4118", "KANEKA CORPORATION", "Basic Materials"],
    ["4151", "Kyowa Kirin Co.,Ltd.", "Healthcare"],
    ["417A", "BLUE ZONES HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["4180", "Appier Group,Inc.", "Technology"],
    ["4182", "Mitsubishi Gas Chemical Company,Inc.", "Basic Materials"],
    ["4183", "Mitsui Chemicals,Inc.", "Basic Materials"],
    ["4186", "TOKYO OHKA KOGYO CO.,LTD.", "Basic Materials"],
    ["4187", "OSAKA ORGANIC CHEMICAL INDUSTRY LTD.", "Basic Materials"],
    ["4188", "Mitsubishi Chemical Group Corporation", "Basic Materials"],
    ["4189", "KH Neochem Co.,Ltd.", "Basic Materials"],
    ["4194", "Visional,Inc.", "Technology"],
    ["4202", "Daicel Corporation", "Basic Materials"],
    ["4203", "Sumitomo Bakelite Company,Limited", "Basic Materials"],
    ["4204", "Sekisui Chemical Co.,Ltd.", "Basic Materials"],
    ["4205", "ZEON CORPORATION", "Basic Materials"],
    ["4206", "Aica Kogyo Company,Limited", "Basic Materials"],
    ["4208", "UBE Corporation", "Basic Materials"],
    ["4212", "Sekisui Jushi Corporation", "Basic Materials"],
    ["4216", "ASAHI YUKIZAI CORPORATION", "Basic Materials"],
    ["4218", "NICHIBAN CO.,LTD.", "Basic Materials"],
    ["4220", "RIKEN TECHNOS CORPORATION", "Basic Materials"],
    ["4221", "Okura Industrial Co.,Ltd.", "Basic Materials"],
    ["4228", "Sekisui Kasei Co.,Ltd.", "Basic Materials"],
    ["4229", "Gun Ei Chemical Industry Co.,Ltd.", "Basic Materials"],
    ["4246", "DaikyoNishikawa Corporation", "Basic Materials"],
    ["4249", "MORIROKU COMPANY,LTD.", "Basic Materials"],
    ["4251", "KEIWA Incorporated", "Basic Materials"],
    ["4272", "NIPPON KAYAKU CO.,LTD.", "Basic Materials"],
    ["4275", "Carlit Co.,Ltd.", "Basic Materials"],
    ["4286", "CL Holdings Inc.", "Industrials"],
    ["4290", "Prestige International Inc.", "Industrials"],
    ["4299", "HIMACS,Ltd.", "Technology"],
    ["429A", "Tekscend Photomask Corp.", "Consumer Cyclical"],
    ["4301", "AMUSE INC.", "Industrials"],
    ["4307", "Nomura Research Institute,Ltd.", "Technology"],
    ["4310", "Dream Incubator Inc.", "Industrials"],
    ["4318", "QUICK CO.,LTD.", "Industrials"],
    ["4323", "Japan System Techniques Co.,Ltd.", "Technology"],
    ["4324", "DENTSU GROUP INC.", "Industrials"],
    ["4326", "INTAGE HOLDINGS Inc.", "Technology"],
    ["4331", "TAKE AND GIVE. NEEDS Co.,Ltd.", "Industrials"],
    ["4337", "PIA CORPORATION", "Industrials"],
    ["4343", "AEON Fantasy Co.,LTD.", "Industrials"],
    ["4344", "SOURCENEXT CORPORATION", "Technology"],
    ["4345", "CTS Co.,Ltd.", "Industrials"],
    ["4350", "MEDICAL SYSTEM NETWORK Co.,Ltd.", "Consumer Cyclical"],
    ["4362", "Nippon Fine Chemical Co.,Ltd.", "Basic Materials"],
    ["4368", "FUSO CHEMICAL CO.,LTD.", "Basic Materials"],
    ["4369", "Tri Chemical Laboratories Inc.", "Basic Materials"],
    ["4373", "Simplex Holdings,Inc.", "Technology"],
    ["4382", "HEROZ,Inc.", "Technology"],
    ["4384", "RAKSUL INC.", "Technology"],
    ["4385", "Mercari,Inc.", "Technology"],
    ["4390", "IPS,Inc.", "Technology"],
    ["4396", "System Support Holdings Inc.", "Technology"],
    ["4401", "ADEKA CORPORATION", "Basic Materials"],
    ["4403", "NOF CORPORATION", "Basic Materials"],
    ["4410", "HARIMA CHEMICALS GROUP,INC.", "Basic Materials"],
    ["4413", "baudroie,inc.", "Technology"],
    ["441A", "NE Inc.", "Technology"],
    ["4420", "eSOL Co.,Ltd.", "Technology"],
    ["4432", "WingArc1st Inc.", "Technology"],
    ["4433", "HITO-Communications Holdings,Inc.", "Industrials"],
    ["4434", "Serverworks Co.,Ltd.", "Technology"],
    ["4443", "Sansan,Inc.", "Technology"],
    ["4449", "giftee Inc.", "Technology"],
    ["4452", "Kao Corporation", "Basic Materials"],
    ["4461", "DKS Co.Ltd.", "Basic Materials"],
    ["4462", "ISHIHARA CHEMICAL CO.,LTD.", "Basic Materials"],
    ["4471", "SANYO CHEMICAL INDUSTRIES,LTD.", "Basic Materials"],
    ["4480", "MEDLEY,INC.", "Technology"],
    ["4481", "BASE CO.,LTD.", "Technology"],
    ["4483", "JMDC Inc.", "Technology"],
    ["4502", "Takeda Pharmaceutical Company Limited", "Healthcare"],
    ["4503", "Astellas Pharma Inc.", "Healthcare"],
    ["4506", "Sumitomo Pharma Co.,Ltd.", "Healthcare"],
    ["4507", "Shionogi & Co.,Ltd.", "Healthcare"],
    ["4516", "Nippon Shinyaku Co.,Ltd.", "Healthcare"],
    ["4519", "CHUGAI PHARMACEUTICAL CO.,LTD.", "Healthcare"],
    ["4521", "KAKEN PHARMACEUTICAL CO.,LTD.", "Healthcare"],
    ["4523", "Eisai Co.,Ltd.", "Healthcare"],
    ["4526", "RIKEN VITAMIN CO.,LTD.", "Consumer Defensive"],
    ["4527", "ROHTO PHARMACEUTICAL CO.,LTD.", "Healthcare"],
    ["4528", "ONO PHARMACEUTICAL CO.,LTD.", "Healthcare"],
    ["4534", "Mochida Pharmaceutical Co.,Ltd.", "Healthcare"],
    ["4536", "SANTEN PHARMACEUTICAL CO.,LTD.", "Healthcare"],
    ["4538", "Fuso Pharmaceutical Industries,Ltd.", "Healthcare"],
    ["4540", "TSUMURA & CO.", "Healthcare"],
    ["4543", "TERUMO CORPORATION", "Technology"],
    ["4544", "H.U. Group Holdings,Inc.", "Industrials"],
    ["4547", "KISSEI PHARMACEUTICAL CO.,LTD.", "Healthcare"],
    ["4548", "SEIKAGAKU CORPORATION", "Healthcare"],
    ["4549", "EIKEN CHEMICAL CO.,LTD.", "Healthcare"],
    ["4552", "JCR Pharmaceuticals Co.,Ltd.", "Healthcare"],
    ["4553", "TOWA PHARMACEUTICAL CO.,LTD.", "Healthcare"],
    ["4554", "Fuji Pharma Co.,Ltd.", "Healthcare"],
    ["4559", "ZERIA PHARMACEUTICAL CO.,LTD.", "Healthcare"],
    ["4565", "Nxera Pharma Co.,Ltd.", "Healthcare"],
    ["4568", "DAIICHI SANKYO COMPANY,LIMITED", "Healthcare"],
    ["4569", "KYORIN Pharmaceutical Co.,Ltd.", "Healthcare"],
    ["4574", "TAIKO PHARMACEUTICAL CO.,LTD.", "Healthcare"],
    ["4577", "Daito Pharmaceutical Co.,Ltd.", "Healthcare"],
    ["4578", "Otsuka Holdings Co.,Ltd.", "Healthcare"],
    ["4587", "PeptiDream Inc.", "Healthcare"],
    ["4611", "Dai Nippon Toryo Company,Limited", "Basic Materials"],
    ["4612", "NIPPON PAINT HOLDINGS CO.,LTD.", "Basic Materials"],
    ["4613", "KANSAI PAINT CO.,LTD.", "Basic Materials"],
    ["4617", "Chugoku Marine Paints,Ltd.", "Basic Materials"],
    ["4620", "FUJIKURA KASEI CO.,LTD.", "Basic Materials"],
    ["4626", "TAIYO HOLDINGS CO.,LTD.", "Basic Materials"],
    ["4631", "DIC Corporation", "Basic Materials"],
    ["4633", "SAKATA INX CORPORATION", "Basic Materials"],
    ["4634", "artience Co.,Ltd.", "Basic Materials"],
    ["4641", "Altech Corporation", "Industrials"],
    ["4651", "SANIX HOLDINGS INCORPORATED", "Industrials"],
    ["4658", "Nippon Air Conditioning Services Co.,Ltd.", "Industrials"],
    ["4661", "ORIENTAL LAND CO.,LTD.", "Industrials"],
    ["4662", "Focus Systems Corporation", "Technology"],
    ["4665", "DUSKIN CO.,LTD.", "Industrials"],
    ["4666", "PARK24 Co.,Ltd.", "Real Estate"],
    ["4668", "MEIKO NETWORK JAPAN CO.,LTD.", "Industrials"],
    ["4671", "FALCO HOLDINGS Co.,Ltd.", "Industrials"],
    ["4674", "CRESCO LTD.", "Technology"],
    ["4676", "FUJI MEDIA HOLDINGS,INC.", "Technology"],
    ["4680", "ROUND ONE Corporation", "Industrials"],
    ["4681", "RESORTTRUST,INC.", "Industrials"],
    ["4684", "OBIC Co.,Ltd.", "Technology"],
    ["4686", "JUSTSYSTEMS CORPORATION", "Technology"],
    ["4687", "TDC SOFT Inc.", "Technology"],
    ["4689", "LY Corporation", "Technology"],
    ["4694", "BML,INC.", "Industrials"],
    ["4704", "Trend Micro Incorporated", "Technology"],
    ["4709", "ID Holdings Corporation", "Technology"],
    ["4714", "RISO KYOIKU GROUP CORPORATION", "Industrials"],
    ["4716", "ORACLE CORPORATION JAPAN", "Technology"],
    ["4718", "WASEDA ACADEMY CO.,LTD.", "Industrials"],
    ["4719", "ALPHA SYSTEMS INC.", "Technology"],
    ["471A", "NS Group,Inc.", "Industrials"],
    ["4722", "Future Corporation", "Technology"],
    ["4725", "CAC Holdings Corporation", "Technology"],
    ["4732", "USS Co.,Ltd.", "Industrials"],
    ["4733", "OBIC BUSINESS CONSULTANTS CO.,LTD.", "Technology"],
    ["4743", "ITFOR Inc.", "Technology"],
    ["4746", "Toukei Computer Co.,Ltd.", "Technology"],
    ["4751", "CyberAgent,Inc.", "Industrials"],
    ["4755", "Rakuten Group,Inc.", "Industrials"],
    ["4763", "CREEK & RIVER Co.,Ltd.", "Industrials"],
    ["4765", "SBI Global Asset Management Co.,Ltd.", "Industrials"],
    ["4767", "TOW CO.,LTD.", "Industrials"],
    ["4768", "OTSUKA CORPORATION", "Technology"],
    ["4776", "Cybozu,Inc.", "Technology"],
    ["4784", "GMO internet,Inc.", "Industrials"],
    ["4792", "YAMADA Consulting Group Co.,Ltd.", "Industrials"],
    ["4801", "CENTRAL SPORTS CO.,LTD.", "Industrials"],
    ["4809", "Paraca Inc.", "Real Estate"],
    ["4812", "DENTSU SOKEN INC.", "Technology"],
    ["4819", "Digital Garage,Inc.", "Technology"],
    ["4820", "EM SYSTEMS CO.,LTD.", "Technology"],
    ["4825", "WEATHERNEWS INC.", "Technology"],
    ["4826", "Computer Institute of Japan, Ltd.", "Technology"],
    ["4828", "Business Engineering Corporation", "Technology"],
    ["4839", "WOWOW INC.", "Technology"],
    ["4845", "Scala,Inc.", "Technology"],
    ["4848", "FULLCAST HOLDINGS CO.,LTD.", "Industrials"],
    ["4849", "en Inc.", "Industrials"],
    ["4880", "CellSource Co.,Ltd.", "Healthcare"],
    ["4886", "ASKA Pharmaceutical Holdings Co.,Ltd.", "Healthcare"],
    ["4887", "SAWAI GROUP HOLDINGS Co.,Ltd.", "Healthcare"],
    ["4901", "FUJIFILM Holdings Corporation", "Basic Materials"],
    ["4902", "KONICA MINOLTA,INC.", "Technology"],
    ["4911", "Shiseido Company,Limited", "Basic Materials"],
    ["4912", "Lion Corporation", "Basic Materials"],
    ["4914", "TAKASAGO INTERNATIONAL CORPORATION", "Basic Materials"],
    ["4917", "MANDOM CORPORATION", "Basic Materials"],
    ["4919", "Milbon Co.,Ltd.", "Basic Materials"],
    ["4922", "KOSE Holdings Corporation", "Basic Materials"],
    ["4923", "COTA CO.,LTD.", "Basic Materials"],
    ["4927", "POLA ORBIS HOLDINGS INC.", "Basic Materials"],
    ["4928", "Noevir Holdings Co.,Ltd.", "Basic Materials"],
    ["4931", "Shinnihonseiyaku Co.,Ltd.", "Basic Materials"],
    ["4933", "I-ne CO.,LTD.", "Basic Materials"],
    ["4936", "AXXZIA Inc.", "Basic Materials"],
    ["4951", "S.T.CORPORATION", "Basic Materials"],
    ["4956", "KONISHI CO.,LTD.", "Basic Materials"],
    ["4958", "T.HASEGAWA CO.,LTD.", "Basic Materials"],
    ["4967", "KOBAYASHI PHARMACEUTICAL CO.,LTD.", "Basic Materials"],
    ["4968", "ARAKAWA CHEMICAL INDUSTRIES,LTD.", "Basic Materials"],
    ["4971", "MEC COMPANY LTD.", "Basic Materials"],
    ["4973", "JAPAN PURE CHEMICAL CO.,LTD.", "Basic Materials"],
    ["4974", "TAKARA BIO INC.", "Basic Materials"],
    ["4975", "JCU CORPORATION", "Basic Materials"],
    ["4979", "OAT Agrio Co.,Ltd.", "Basic Materials"],
    ["4980", "Dexerials Corporation", "Basic Materials"],
    ["4985", "Earth Corporation", "Basic Materials"],
    ["4992", "HOKKO CHEMICAL INDUSTRY CO.,LTD.", "Basic Materials"],
    ["4994", "Taisei Lamick Group Head Quarter & Innovation Co.,Ltd.", "Basic Materials"],
    ["4996", "KUMIAI CHEMICAL INDUSTRY CO.,LTD.", "Basic Materials"],
    ["4997", "NIHON NOHYAKU CO.,LTD.", "Basic Materials"],
    ["5011", "NICHIREKI GROUP CO.,LTD.", "Energy"],
    ["5013", "Yushiro Inc.", "Energy"],
    ["5016", "JX Advanced Metals Corporation", "Basic Materials"],
    ["5019", "Idemitsu Kosan Co.,Ltd.", "Energy"],
    ["5020", "ENEOS Holdings,Inc.", "Energy"],
    ["5021", "COSMO ENERGY HOLDINGS COMPANY,LIMITED", "Energy"],
    ["5032", "ANYCOLOR Inc.", "Technology"],
    ["5036", "Japan Business Systems,Inc.", "Technology"],
    ["5074", "TESS Holdings Co.,Ltd.", "Industrials"],
    ["5076", "INFRONEER Holdings Inc.", "Industrials"],
    ["5101", "The Yokohama Rubber Company,Limited", "Consumer Cyclical"],
    ["5105", "Toyo Tire Corporation", "Consumer Cyclical"],
    ["5108", "BRIDGESTONE CORPORATION", "Consumer Cyclical"],
    ["5110", "Sumitomo Rubber Industries,Ltd.", "Consumer Cyclical"],
    ["5121", "FUJIKURA COMPOSITES Inc.", "Consumer Cyclical"],
    ["5122", "OKAMOTO INDUSTRIES,INC.", "Consumer Cyclical"],
    ["5142", "Achilles Corporation", "Basic Materials"],
    ["5185", "Fukoku Co.,Ltd.", "Consumer Cyclical"],
    ["5186", "Nitta Corporation", "Consumer Cyclical"],
    ["5192", "Mitsuboshi Belting Ltd.", "Consumer Cyclical"],
    ["5195", "Bando Chemical Industries,Ltd.", "Consumer Cyclical"],
    ["5201", "AGC Inc.", "Basic Materials"],
    ["5202", "Nippon Sheet Glass Company,Limited", "Basic Materials"],
    ["5208", "Arisawa Mfg.Co.,Ltd.", "Basic Materials"],
    ["5214", "Nippon Electric Glass Co.,Ltd.", "Basic Materials"],
    ["5218", "OHARA INC.", "Basic Materials"],
    ["5232", "Sumitomo Osaka Cement Co.,Ltd.", "Basic Materials"],
    ["5233", "TAIHEIYO CEMENT CORPORATION", "Basic Materials"],
    ["5262", "Nippon Hume Corporation", "Basic Materials"],
    ["5269", "NIPPON CONCRETE INDUSTRIES CO.,LTD.", "Basic Materials"],
    ["5273", "MITANI SEKISAN CO.,LTD.", "Basic Materials"],
    ["5288", "ASIA PILE HOLDINGS CORPORATION", "Basic Materials"],
    ["5301", "TOKAI CARBON CO.,LTD.", "Basic Materials"],
    ["5302", "Nippon Carbon Co.,Ltd.", "Basic Materials"],
    ["5310", "TOYO TANSO CO.,LTD.", "Basic Materials"],
    ["5331", "NORITAKE CO.,LIMITED", "Basic Materials"],
    ["5332", "TOTO LTD.", "Basic Materials"],
    ["5333", "NGK Corporation", "Basic Materials"],
    ["5334", "Niterra Co.,Ltd.", "Basic Materials"],
    ["5344", "MARUWA CO.,LTD.", "Basic Materials"],
    ["5351", "SHINAGAWA REFRA CO.,LTD.", "Basic Materials"],
    ["5357", "YOTAI REFRACTORIES CO.,LTD.", "Basic Materials"],
    ["5384", "FUJIMI INCORPORATED", "Basic Materials"],
    ["5393", "NICHIAS CORPORATION", "Basic Materials"],
    ["5401", "NIPPON STEEL CORPORATION", "Basic Materials"],
    ["5406", "Kobe Steel,Ltd.", "Basic Materials"],
    ["5408", "NAKAYAMA STEEL WORKS,LTD.", "Basic Materials"],
    ["5410", "Godo Steel,Ltd.", "Basic Materials"],
    ["5411", "JFE Holdings,Inc.", "Basic Materials"],
    ["5423", "TOKYO STEEL MANUFACTURING CO.,LTD.", "Basic Materials"],
    ["543A", "ARCHION Corporation", "Industrials"],
    ["5440", "KYOEI STEEL LTD.", "Basic Materials"],
    ["5444", "YAMATO KOGYO CO.,LTD.", "Basic Materials"],
    ["5445", "TOKYO TEKKO CO.,LTD.", "Basic Materials"],
    ["5449", "OSAKA STEEL CO.,LTD.", "Basic Materials"],
    ["544A", "GMS Group Co.,Ltd.", "Industrials"],
    ["5451", "YODOKO,Ltd.", "Basic Materials"],
    ["545A", "Toranvia Co.,Ltd.", "Technology"],
    ["5461", "Chubu Steel Plate Co.,Ltd.", "Basic Materials"],
    ["5463", "Maruichi Steel Tube Ltd.", "Basic Materials"],
    ["5464", "MORY INDUSTRIES INC.", "Basic Materials"],
    ["546A", "MIRAINI HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["5471", "Daido Steel Co.,Ltd.", "Basic Materials"],
    ["547A", "Muninova Holdings Inc.", "Industrials"],
    ["5480", "Nippon Yakin kogyo Co.,Ltd.", "Basic Materials"],
    ["5482", "AICHI STEEL CORPORATION", "Basic Materials"],
    ["5541", "PACIFIC METALS CO.,LTD.", "Basic Materials"],
    ["5563", "Nippon Denko Co.,Ltd.", "Basic Materials"],
    ["5602", "Kurimoto,Ltd.", "Basic Materials"],
    ["5631", "The Japan Steel Works,Ltd.", "Industrials"],
    ["5632", "Mitsubishi Steel Mfg.Co.,Ltd.", "Basic Materials"],
    ["5659", "Nippon Seisen Co.,Ltd.", "Basic Materials"],
    ["5698", "ENVIPRO HOLDINGS Inc.", "Basic Materials"],
    ["5702", "DAIKI ALUMINIUM INDUSTRY CO.,LTD.", "Basic Materials"],
    ["5703", "Nippon Light Metal Holdings Company,Ltd.", "Basic Materials"],
    ["5706", "Mitsui Kinzoku Company,Limited", "Basic Materials"],
    ["5707", "Toho Zinc Co.,Ltd.", "Basic Materials"],
    ["5711", "Mitsubishi Materials Corporation", "Basic Materials"],
    ["5713", "Sumitomo Metal Mining Co.,Ltd.", "Basic Materials"],
    ["5714", "DOWA HOLDINGS CO.,LTD.", "Basic Materials"],
    ["5715", "FURUKAWA CO.,LTD.", "Basic Materials"],
    ["5726", "OSAKA Titanium technologies Co.,Ltd.", "Basic Materials"],
    ["5727", "TOHO TITANIUM COMPANY,LIMITED", "Basic Materials"],
    ["5741", "UACJ Corporation", "Basic Materials"],
    ["5757", "CK SAN-ETSU Co.,Ltd.", "Basic Materials"],
    ["5801", "Furukawa Electric Co.,Ltd.", "Basic Materials"],
    ["5802", "Sumitomo Electric Industries,Ltd.", "Basic Materials"],
    ["5803", "Fujikura Ltd.", "Basic Materials"],
    ["5805", "SWCC Corporation", "Basic Materials"],
    ["5821", "HIRAKAWA HEWTECH CORP.", "Basic Materials"],
    ["5830", "Iyogin Holdings,Inc.", "Financial Services"],
    ["5831", "Shizuoka Financial Group,Inc.", "Financial Services"],
    ["5832", "Chugin Financial Group,Inc.", "Financial Services"],
    ["5838", "Rakuten Bank,Ltd.", "Financial Services"],
    ["5844", "Kyoto Financial Group,Inc.", "Financial Services"],
    ["5851", "RYOBI LIMITED", "Basic Materials"],
    ["5857", "ARE Holdings,Inc.", "Basic Materials"],
    ["5889", "Japan Eyewear Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["5901", "Toyo Seikan Group Holdings,Ltd.", "Industrials"],
    ["5902", "HOKKAN HOLDINGS LIMITED", "Industrials"],
    ["5909", "CORONA CORPORATION", "Industrials"],
    ["5911", "Yokogawa Bridge Holdings Corp.", "Industrials"],
    ["5929", "Sanwa Holdings Corporation", "Industrials"],
    ["5930", "Bunka Shutter Co.,Ltd.", "Industrials"],
    ["5932", "Sankyo Tateyama,Inc.", "Industrials"],
    ["5933", "ALINCO INCORPORATED", "Industrials"],
    ["5938", "LIXIL Corporation", "Industrials"],
    ["5943", "NORITZ CORPORATION", "Industrials"],
    ["5946", "CHOFU SEISAKUSHO CO.,LTD.", "Industrials"],
    ["5947", "RINNAI CORPORATION", "Industrials"],
    ["5949", "UNIPRES CORPORATION", "Industrials"],
    ["5957", "NITTOSEIKO CO.,LTD.", "Industrials"],
    ["5959", "OKABE CO.,LTD.", "Industrials"],
    ["5970", "G-TEKT CORPORATION", "Industrials"],
    ["5975", "Topre Corporation", "Industrials"],
    ["5976", "Neturen Co.,Ltd.", "Industrials"],
    ["5981", "TOKYO ROPE MFG.CO.,LTD", "Industrials"],
    ["5985", "SUNCALL CORPORATION", "Industrials"],
    ["5988", "PIOLAX,INC.", "Industrials"],
    ["5989", "H-ONE CO.,LTD.", "Industrials"],
    ["5991", "NHK SPRING CO.,LTD.", "Industrials"],
    ["5992", "CHUO SPRING CO.,LTD.", "Industrials"],
    ["6005", "MIURA CO.,LTD.", "Industrials"],
    ["6013", "TAKUMA CO.,LTD.", "Industrials"],
    ["6027", "Bengo4.com,Inc.", "Industrials"],
    ["6035", "IR Japan Holdings,Ltd.", "Industrials"],
    ["6036", "KeePer Technical Laboratory Co.,Ltd.", "Industrials"],
    ["6047", "Gunosy Inc.", "Industrials"],
    ["6050", "E-Guardian Inc.", "Industrials"],
    ["6055", "JAPAN MATERIAL Co.,Ltd.", "Industrials"],
    ["6058", "VECTOR INC.", "Industrials"],
    ["6062", "CHARM CARE CORPORATION", "Industrials"],
    ["6070", "CAREERLINK CO.,LTD.", "Industrials"],
    ["6071", "IBJ,Inc.", "Industrials"],
    ["6073", "ASANTE INCORPORATED", "Industrials"],
    ["6078", "Value HR Co.,Ltd.", "Industrials"],
    ["6080", "M&A Capital Partners Co.,Ltd.", "Industrials"],
    ["6082", "RIDE ON EXPRESS HOLDINGS Co.,Ltd.", "Industrials"],
    ["6088", "SIGMAXYZ Holdings Inc.", "Industrials"],
    ["6089", "WILL GROUP,INC.", "Industrials"],
    ["6098", "Recruit Holdings Co.,Ltd.", "Industrials"],
    ["6099", "ELAN Corporation", "Industrials"],
    ["6101", "TSUGAMI CORPORATION", "Industrials"],
    ["6103", "OKUMA Corporation", "Industrials"],
    ["6104", "SHIBAURA MACHINE CO.,LTD.", "Industrials"],
    ["6113", "AMADA CO.,LTD.", "Industrials"],
    ["6118", "AIDA ENGINEERING,LTD.", "Industrials"],
    ["6134", "FUJI CORPORATION", "Industrials"],
    ["6135", "Makino Milling Machine Co.,Ltd.", "Industrials"],
    ["6136", "OSG Corporation", "Industrials"],
    ["6140", "Asahi Diamond Industrial Co.,Ltd.", "Industrials"],
    ["6141", "DMG MORI CO.,LTD.", "Industrials"],
    ["6143", "Sodick Co.,Ltd.", "Industrials"],
    ["6146", "DISCO CORPORATION", "Industrials"],
    ["6151", "NITTO KOHKI CO.,LTD.", "Industrials"],
    ["6157", "NS TOOL CO.,LTD.", "Industrials"],
    ["6167", "Fuji Die Co.,Ltd.", "Industrials"],
    ["6178", "JAPAN POST HOLDINGS Co.,Ltd.", "Industrials"],
    ["6183", "BELLSYSTEM24 HOLDINGS,INC.", "Industrials"],
    ["6184", "Kamakura Shinsho,Ltd.", "Industrials"],
    ["6191", "AirTrip Corp.", "Industrials"],
    ["6194", "Atrae,Inc.", "Industrials"],
    ["6196", "Strike Group Co.,Ltd.", "Industrials"],
    ["6197", "Solasto Corporation", "Industrials"],
    ["6199", "SERAKU Co.,Ltd.", "Technology"],
    ["6200", "Insource Co.,Ltd.", "Industrials"],
    ["6201", "TOYOTA INDUSTRIES CORPORATION", "Industrials"],
    ["6209", "NPR-RIKEN CORPORATION", "Industrials"],
    ["6222", "SHIMA SEIKI MFG.,LTD.", "Industrials"],
    ["6235", "OPTORUN CO.,LTD.", "Industrials"],
    ["6237", "IWAKI CO.,LTD.", "Industrials"],
    ["6238", "FURYU CORPORATION", "Industrials"],
    ["6240", "YAMASHIN-FILTER CORP.", "Industrials"],
    ["6247", "HISAKA WORKS,LTD.", "Industrials"],
    ["6250", "YAMABIKO CORPORATION", "Industrials"],
    ["6254", "Nomura Micro Science Co.,Ltd.", "Industrials"],
    ["6258", "HIRATA Corporation", "Industrials"],
    ["6262", "PEGASUS CO.,LTD.", "Industrials"],
    ["6264", "Marumae Co.,Ltd.", "Industrials"],
    ["6266", "TAZMO CO.,LTD.", "Industrials"],
    ["6268", "Nabtesco Corporation", "Industrials"],
    ["6269", "MODEC,INC.", "Industrials"],
    ["6272", "RHEON AUTOMATIC MACHINERY CO.,LTD.", "Industrials"],
    ["6273", "SMC CORPORATION", "Industrials"],
    ["6277", "HOSOKAWA MICRON CORPORATION", "Industrials"],
    ["6278", "UNION TOOL CO.", "Industrials"],
    ["6279", "ZUIKO CORPORATION", "Industrials"],
    ["6282", "OILES CORPORATION", "Industrials"],
    ["6284", "NISSEI ASB MACHINE CO.,LTD.", "Industrials"],
    ["6287", "SATO CORPORATION", "Industrials"],
    ["6289", "GIKEN LTD.", "Industrials"],
    ["6291", "AIRTECH JAPAN,LTD.", "Industrials"],
    ["6298", "Y.A.C.HOLDINGS CO.,LTD.", "Industrials"],
    ["6301", "KOMATSU LTD.", "Industrials"],
    ["6302", "SUMITOMO HEAVY INDUSTRIES,LTD.", "Industrials"],
    ["6305", "Hitachi Construction Machinery Co.,Ltd.", "Industrials"],
    ["6306", "NIKKO CO.,LTD.", "Industrials"],
    ["6309", "TOMOE ENGINEERING CO.,LTD.(TOMOE KOGYO CO.,LTD.)", "Industrials"],
    ["6310", "ISEKI & CO.,LTD.", "Industrials"],
    ["6315", "TOWA CORPORATION", "Industrials"],
    ["6317", "Kitagawa Corporation", "Industrials"],
    ["6323", "RORZE CORPORATION", "Industrials"],
    ["6324", "Harmonic Drive Systems Inc.", "Industrials"],
    ["6326", "KUBOTA CORPORATION", "Industrials"],
    ["6328", "EBARA JITSUGYO CO.,LTD.", "Industrials"],
    ["6330", "TOYO ENGINEERING CORPORATION", "Industrials"],
    ["6331", "Mitsubishi Kakoki Kaisha,Ltd.", "Industrials"],
    ["6332", "TSUKISHIMA HOLDINGS CO.,LTD.", "Industrials"],
    ["6333", "TEIKOKU CORPORATION", "Industrials"],
    ["6339", "Sintokogio,Ltd.", "Industrials"],
    ["6340", "SHIBUYA CORPORATION", "Industrials"],
    ["6345", "AICHI CORPORATION", "Industrials"],
    ["6349", "KOMORI CORPORATION", "Industrials"],
    ["6351", "TSURUMI MANUFACTURING CO.,LTD.", "Industrials"],
    ["6358", "SAKAI HEAVY INDUSTRIES,LTD.", "Industrials"],
    ["6361", "EBARA CORPORATION", "Industrials"],
    ["6363", "Torishima Pump Mfg.Co.,Ltd.", "Industrials"],
    ["6364", "AIRMAN CORPORATION", "Industrials"],
    ["6367", "DAIKIN INDUSTRIES,LTD.", "Industrials"],
    ["6368", "ORGANO CORPORATION", "Industrials"],
    ["6369", "TOYO KANETSU K.K.", "Industrials"],
    ["6370", "Kurita Water Industries Ltd.", "Industrials"],
    ["6371", "TSUBAKIMOTO CHAIN CO.", "Industrials"],
    ["6376", "NIKKISO CO.,LTD.", "Technology"],
    ["6378", "KIMURA CHEMICAL PLANTS CO.,LTD.", "Industrials"],
    ["6379", "RAIZNEXT Corporation", "Industrials"],
    ["6381", "ANEST IWATA Corporation", "Industrials"],
    ["6383", "DAIFUKU CO.,LTD.", "Industrials"],
    ["6387", "SAMCO INC.", "Industrials"],
    ["6395", "TADANO LTD.", "Industrials"],
    ["6407", "CKD Corporation", "Industrials"],
    ["6412", "Heiwa Corporation", "Industrials"],
    ["6413", "RISO KAGAKU CORPORATION", "Industrials"],
    ["6417", "SANKYO CO.,LTD.", "Industrials"],
    ["6418", "JAPAN CASH MACHINE CO.,LTD.", "Industrials"],
    ["6419", "Mars Group Holdings Corporation", "Industrials"],
    ["6420", "GALILEI CO.LTD.", "Industrials"],
    ["6430", "DAIKOKU DENKI CO.,LTD.", "Industrials"],
    ["6432", "TAKEUCHI MFG.CO.,LTD.", "Industrials"],
    ["6436", "Amano Corporation", "Industrials"],
    ["6440", "JUKI CORPORATION", "Industrials"],
    ["6445", "JANOME Corporation", "Industrials"],
    ["6448", "BROTHER INDUSTRIES,LTD.", "Technology"],
    ["6454", "MAX CO.,LTD.", "Industrials"],
    ["6455", "MORITA HOLDINGS CORPORATION", "Industrials"],
    ["6457", "GLORY LTD.", "Industrials"],
    ["6458", "SINKO INDUSTRIES LTD.", "Industrials"],
    ["6459", "DAIWA INDUSTRIES LTD.", "Industrials"],
    ["6460", "SEGA SAMMY HOLDINGS INC.", "Industrials"],
    ["6463", "TPR CO.,LTD.", "Industrials"],
    ["6464", "TSUBAKI NAKASHIMA CO.,LTD.", "Industrials"],
    ["6465", "HOSHIZAKI CORPORATION", "Industrials"],
    ["6470", "TAIHO KOGYO CO.,LTD.", "Industrials"],
    ["6471", "NSK Ltd.", "Industrials"],
    ["6472", "NTN CORPORATION", "Industrials"],
    ["6473", "JTEKT Corporation", "Industrials"],
    ["6474", "NACHI-FUJIKOSHI CORP.", "Industrials"],
    ["6479", "MINEBEA MITSUMI Inc.", "Technology"],
    ["6480", "NIPPON THOMPSON CO.,LTD.", "Industrials"],
    ["6481", "THK CO.,LTD.", "Industrials"],
    ["6482", "Yushin Company", "Industrials"],
    ["6485", "MAEZAWA KYUSO INDUSTRIES CO.,LTD.", "Industrials"],
    ["6486", "EAGLE INDUSTRY CO.,LTD.", "Industrials"],
    ["6490", "PILLAR Corporation", "Industrials"],
    ["6498", "KITZ CORPORATION", "Industrials"],
    ["6501", "Hitachi,Ltd.", "Technology"],
    ["6503", "Mitsubishi Electric Corporation", "Technology"],
    ["6504", "FUJI ELECTRIC CO.,LTD.", "Technology"],
    ["6506", "YASKAWA Electric Corporation", "Technology"],
    ["6507", "SINFONIA TECHNOLOGY CO.,LTD.", "Technology"],
    ["6508", "MEIDENSHA CORPORATION", "Technology"],
    ["6516", "SANYO DENKI CO.,LTD.", "Technology"],
    ["6517", "Denyo Co.,Ltd.", "Technology"],
    ["6523", "PHC Holdings Corporation", "Technology"],
    ["6525", "KOKUSAI ELECTRIC CORPORATION", "Technology"],
    ["6526", "Socionext Inc.", "Technology"],
    ["6532", "BayCurrent,Inc.", "Industrials"],
    ["6533", "Orchestra Holdings Inc.", "Industrials"],
    ["6535", "i-mobile Co.,Ltd.", "Industrials"],
    ["6539", "MATCHING SERVICE JAPAN CO.,LTD.", "Industrials"],
    ["6544", "JAPAN ELEVATOR SERVICE HOLDINGS CO.,LTD.", "Industrials"],
    ["6560", "LTS,Inc.", "Industrials"],
    ["6564", "MIDAC HOLDINGS CO.,LTD.", "Industrials"],
    ["6571", "QB Net Holdings Co.,Ltd.", "Industrials"],
    ["6572", "OPEN Group,Inc.", "Industrials"],
    ["6584", "Sanoh Industrial Co.,Ltd.", "Industrials"],
    ["6586", "Makita Corporation", "Industrials"],
    ["6588", "TOSHIBA TEC CORPORATION", "Technology"],
    ["6590", "SHIBAURA MECHATRONICS CORPORATION", "Technology"],
    ["6592", "MABUCHI MOTOR CO.,LTD.", "Technology"],
    ["6615", "UMC Electronics Co.,Ltd.", "Technology"],
    ["6616", "TOREX SEMICONDUCTOR LTD.", "Technology"],
    ["6617", "TAKAOKA TOKO CO.,LTD.", "Technology"],
    ["6619", "W-SCOPE Corporation", "Technology"],
    ["6620", "Miyakoshi Holdings,Inc.", "Real Estate"],
    ["6622", "DAIHEN CORPORATION", "Technology"],
    ["6630", "YA-MAN LTD.", "Technology"],
    ["6632", "JVCKENWOOD Corporation", "Technology"],
    ["6638", "MIMAKI ENGINEERING CO.,LTD.", "Technology"],
    ["6644", "Osaki Electric Co.,Ltd.", "Technology"],
    ["6645", "OMRON Corporation", "Technology"],
    ["6651", "NITTO KOGYO CORPORATION", "Technology"],
    ["6652", "IDEC CORPORATION", "Technology"],
    ["6674", "GS Yuasa Corporation", "Technology"],
    ["6676", "BUFFALO INC.", "Technology"],
    ["6678", "Techno Medica Co.,Ltd.", "Technology"],
    ["6699", "DIAMOND ELECTRIC HOLDINGS Co.,Ltd.", "Technology"],
    ["6701", "NEC Corporation", "Technology"],
    ["6702", "Fujitsu Limited", "Technology"],
    ["6703", "Oki Electric Industry Company,Limited", "Technology"],
    ["6706", "DKK Co.,Ltd.", "Technology"],
    ["6707", "Sanken Electric Co.,Ltd.", "Technology"],
    ["6718", "AIPHONE CO.,LTD.", "Technology"],
    ["6723", "Renesas Electronics Corporation", "Technology"],
    ["6724", "SEIKO EPSON CORPORATION", "Technology"],
    ["6727", "Wacom Co.,Ltd.", "Technology"],
    ["6728", "ULVAC, Inc.", "Technology"],
    ["6730", "AXELL CORPORATION", "Technology"],
    ["6737", "EIZO Corporation", "Technology"],
    ["6740", "Japan Display Inc.", "Technology"],
    ["6741", "Nippon Signal Company,Limited", "Technology"],
    ["6742", "Kyosan Electric Manufacturing Co.,Ltd.", "Technology"],
    ["6744", "NOHMI BOSAI LTD.", "Technology"],
    ["6745", "HOCHIKI CORPORATION", "Technology"],
    ["6750", "ELECOM CO.,LTD.", "Technology"],
    ["6752", "Panasonic Holdings Corporation", "Technology"],
    ["6753", "Sharp Corporation", "Technology"],
    ["6754", "ANRITSU CORPORATION", "Technology"],
    ["6758", "SONY GROUP CORPORATION", "Technology"],
    ["6762", "TDK Corporation", "Technology"],
    ["6763", "Teikoku Tsushin Kogyo Co.,Ltd.", "Technology"],
    ["6768", "TAMURA CORPORATION", "Technology"],
    ["6770", "ALPS ALPINE CO.,LTD.", "Technology"],
    ["6779", "NIHON DEMPA KOGYO CO.,LTD.", "Technology"],
    ["6785", "SUZUKI CO.,LTD.", "Technology"],
    ["6787", "Meiko Electronics Co.,Ltd.", "Technology"],
    ["6788", "NIHON TRIM CO.,LTD.", "Technology"],
    ["6794", "Foster Electric Company,Limited", "Technology"],
    ["6798", "SMK Corporation", "Technology"],
    ["6800", "YOKOWO CO.,LTD.", "Technology"],
    ["6804", "Hosiden Corporation", "Technology"],
    ["6806", "HIROSE ELECTRIC CO.,LTD.", "Technology"],
    ["6807", "Japan Aviation Electronics Industry,Limited", "Technology"],
    ["6809", "TOA CORPORATION", "Technology"],
    ["6810", "Maxell,Ltd.", "Technology"],
    ["6814", "FURUNO ELECTRIC CO.,LTD.", "Technology"],
    ["6817", "SUMIDA CORPORATION", "Technology"],
    ["6820", "ICOM INCORPORATED", "Technology"],
    ["6823", "RION CO.,LTD.", "Technology"],
    ["6841", "YOKOGAWA ELECTRIC CORPORATION", "Technology"],
    ["6844", "Shindengen Electric Manufacturing Co.,Ltd.", "Technology"],
    ["6845", "Azbil Corporation", "Technology"],
    ["6849", "NIHON KOHDEN CORPORATION", "Technology"],
    ["6850", "Chino Corporation", "Technology"],
    ["6855", "JAPAN ELECTRONIC MATERIALS CORPORATION", "Technology"],
    ["6856", "HORIBA,Ltd.", "Technology"],
    ["6857", "ADVANTEST CORPORATION", "Technology"],
    ["6859", "ESPEC CORP.", "Technology"],
    ["6861", "KEYENCE CORPORATION", "Technology"],
    ["6866", "HIOKI E.E.CORPORATION", "Technology"],
    ["6869", "SYSMEX CORPORATION", "Technology"],
    ["6871", "MICRONICS JAPAN CO.,LTD.", "Technology"],
    ["6875", "MegaChips Corporation", "Technology"],
    ["6877", "Obara Group Incorporated", "Technology"],
    ["6902", "DENSO CORPORATION", "Industrials"],
    ["6905", "COSEL CO.,LTD.", "Technology"],
    ["6908", "IRISO ELECTRONICS CO.,LTD.", "Technology"],
    ["6914", "OPTEX GROUP Company,Limited", "Technology"],
    ["6915", "CHIYODA INTEGRE CO.,LTD.", "Technology"],
    ["6920", "Lasertec Corporation", "Technology"],
    ["6923", "Stanley Electric Co.,Ltd.", "Technology"],
    ["6925", "USHIO INC.", "Technology"],
    ["6929", "NIPPON CERAMIC CO.,LTD.", "Technology"],
    ["6941", "YAMAICHI ELECTRONICS CO.,LTD.", "Technology"],
    ["6947", "ZUKEN INC.", "Technology"],
    ["6951", "JEOL Ltd.", "Technology"],
    ["6952", "CASIO COMPUTER CO.,LTD.", "Technology"],
    ["6954", "FANUC CORPORATION", "Technology"],
    ["6958", "CMK CORPORATION", "Technology"],
    ["6961", "ENPLAS CORPORATION", "Technology"],
    ["6962", "DAISHINKU CORP.", "Technology"],
    ["6963", "ROHM COMPANY LIMITED", "Technology"],
    ["6965", "HAMAMATSU PHOTONICS K.K.", "Technology"],
    ["6966", "Mitsui High-tec,Inc.", "Technology"],
    ["6971", "KYOCERA CORPORATION", "Technology"],
    ["6976", "TAIYO YUDEN CO.,LTD.", "Technology"],
    ["6981", "Murata Manufacturing Co.,Ltd.", "Technology"],
    ["6986", "FUTABA CORPORATION", "Technology"],
    ["6988", "NITTO DENKO CORPORATION", "Basic Materials"],
    ["6995", "TOKAI RIKA CO.,LTD.", "Industrials"],
    ["6996", "NICHICON CORPORATION", "Technology"],
    ["6997", "NIPPON CHEMI-CON CORPORATION", "Technology"],
    ["6999", "KOA CORPORATION", "Technology"],
    ["7003", "MITSUI E&S Co.,Ltd.", "Industrials"],
    ["7004", "Kanadevia Corporation", "Industrials"],
    ["7011", "Mitsubishi Heavy Industries,Ltd.", "Industrials"],
    ["7012", "Kawasaki Heavy Industries,Ltd.", "Industrials"],
    ["7013", "IHI Corporation", "Industrials"],
    ["7014", "Namura Shipbuilding Co.,Ltd.", "Industrials"],
    ["7033", "Management Solutions Co.,Ltd.", "Industrials"],
    ["7034", "Prored Partners CO.,LTD.", "Industrials"],
    ["7038", "Frontier Management Inc.", "Industrials"],
    ["7071", "Amvis Holdings,Inc.", "Industrials"],
    ["7085", "CURVES HOLDINGS Co.,Ltd.", "Industrials"],
    ["7095", "Macbee Planet,Inc.", "Industrials"],
    ["7102", "NIPPON SHARYO,LTD.", "Industrials"],
    ["7128", "UNISOL Holdings Corporation", "Consumer Cyclical"],
    ["7130", "YAMAE GROUP HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["7148", "Financial Partners Group Co.,Ltd.", "Financial Services"],
    ["7157", "LIFENET INSURANCE COMPANY", "Financial Services"],
    ["7164", "ZENKOKU HOSHO Co.,Ltd.", "Industrials"],
    ["7167", "Mebuki Financial Group,Inc.", "Financial Services"],
    ["7172", "Japan Investment Adviser Co.,Ltd.", "Financial Services"],
    ["7173", "Tokyo Kiraboshi Financial Group,Inc.", "Financial Services"],
    ["7180", "Kyushu Financial Group,Inc.", "Financial Services"],
    ["7181", "JAPAN POST INSURANCE Co.,Ltd.", "Financial Services"],
    ["7182", "JAPAN POST BANK Co.,Ltd.", "Financial Services"],
    ["7184", "THE FIRST BANK OF TOYAMA,LTD.", "Financial Services"],
    ["7186", "Yokohama Financial Group,Inc.", "Financial Services"],
    ["7187", "J-LEASE CO.,LTD.", "Industrials"],
    ["7189", "Nishi-Nippon Financial Holdings,Inc.", "Financial Services"],
    ["7198", "SBI ARUHI Corporation", "Industrials"],
    ["7199", "Premium Group Co.,Ltd.", "Industrials"],
    ["7201", "NISSAN MOTOR CO.,LTD.", "Industrials"],
    ["7202", "ISUZU MOTORS LIMITED", "Industrials"],
    ["7203", "TOYOTA MOTOR CORPORATION", "Industrials"],
    ["7211", "MITSUBISHI MOTORS CORPORATION", "Industrials"],
    ["7220", "MUSASHI SEIMITSU INDUSTRY CO.,LTD.", "Industrials"],
    ["7222", "NISSAN SHATAI CO.,LTD.", "Industrials"],
    ["7224", "ShinMaywa Industries,LTD.", "Industrials"],
    ["7226", "KYOKUTO KAIHATSU KOGYO CO.,LTD.", "Industrials"],
    ["7231", "TOPY INDUSTRIES,LIMITED", "Industrials"],
    ["7236", "T.RAD Co., Ltd.", "Industrials"],
    ["7238", "AKEBONO BRAKE INDUSTRY CO.,LTD.", "Industrials"],
    ["7239", "TACHI-S CO.,LTD.", "Industrials"],
    ["7240", "NOK CORPORATION", "Industrials"],
    ["7241", "FUTABA INDUSTRIAL CO.,LTD.", "Industrials"],
    ["7242", "KYB Corporation", "Industrials"],
    ["7244", "ICHIKOH INDUSTRIES,LTD.", "Technology"],
    ["7245", "DAIDO METAL CO.,LTD.", "Industrials"],
    ["7246", "PRESS KOGYO CO.,LTD.", "Industrials"],
    ["7259", "AISIN CORPORATION", "Industrials"],
    ["7261", "Mazda Motor Corporation", "Industrials"],
    ["7267", "HONDA MOTOR CO.,LTD.", "Industrials"],
    ["7269", "SUZUKI MOTOR CORPORATION", "Industrials"],
    ["7270", "SUBARU CORPORATION", "Industrials"],
    ["7272", "Yamaha Motor Co.,Ltd.", "Industrials"],
    ["7276", "KOITO MANUFACTURING CO.,LTD.", "Technology"],
    ["7278", "EXEDY Corporation", "Industrials"],
    ["7280", "MITSUBA Corporation", "Technology"],
    ["7282", "TOYODA GOSEI CO.,LTD.", "Industrials"],
    ["7283", "AISAN INDUSTRY CO.,LTD.", "Industrials"],
    ["7294", "YOROZU CORPORATION", "Industrials"],
    ["7296", "F.C.C.CO.,LTD.", "Industrials"],
    ["7309", "SHIMANO INC.", "Industrials"],
    ["7313", "TS TECH CO.,LTD.", "Industrials"],
    ["7322", "San ju San Financial Group,Inc.", "Financial Services"],
    ["7327", "Daishi Hokuetsu Financial Group,Inc.", "Financial Services"],
    ["7337", "Hirogin Holdings,Inc.", "Financial Services"],
    ["7350", "Okinawa Financial Group,Inc.", "Financial Services"],
    ["7354", "Direct Marketing MiX Inc.", "Industrials"],
    ["7358", "Poppins Corporation", "Industrials"],
    ["7366", "LITALICO Inc.", "Industrials"],
    ["7380", "Juroku Financial Group,Inc.", "Financial Services"],
    ["7381", "CCI Group,Inc.", "Financial Services"],
    ["7383", "Net Protections Holdings,Inc.", "Industrials"],
    ["7384", "Procrea Holdings,Inc.", "Financial Services"],
    ["7388", "FP Partner Inc.", "Financial Services"],
    ["7389", "Aichi Financial Group,Inc.", "Financial Services"],
    ["7414", "ONOKEN CO.,LTD.", "Consumer Cyclical"],
    ["7419", "Nojima Co.,Ltd.", "Consumer Cyclical"],
    ["7421", "KAPPA�ECREATE CO.,LTD.", "Consumer Cyclical"],
    ["7433", "Hakuto Co.,Ltd.", "Consumer Cyclical"],
    ["7438", "KONDOTEC INC.", "Consumer Cyclical"],
    ["7447", "NAGAILEBEN Co.,Ltd.", "Consumer Cyclical"],
    ["7453", "RYOHIN KEIKAKU CO.,LTD.", "Consumer Cyclical"],
    ["7456", "MATSUDA SANGYO Co.,Ltd.", "Consumer Cyclical"],
    ["7458", "DAIICHIKOSHO CO.,LTD.", "Consumer Cyclical"],
    ["7459", "MEDIPAL HOLDINGS CORPORATION", "Consumer Cyclical"],
    ["7463", "ADVAN GROUP CO.,LTD.", "Consumer Cyclical"],
    ["7466", "SPK CORPORATION", "Consumer Cyclical"],
    ["7475", "ALBIS Co.,Ltd.", "Consumer Cyclical"],
    ["7476", "AS ONE CORPORATION", "Consumer Cyclical"],
    ["7480", "SUZUDEN CORPORATION", "Consumer Cyclical"],
    ["7482", "SHIMOJIMA Co.,Ltd.", "Consumer Cyclical"],
    ["7483", "DOSHISHA CO.,LTD.", "Consumer Cyclical"],
    ["7504", "KOHSOKU CORPORATION", "Consumer Cyclical"],
    ["7508", "G-7 HOLDINGS Inc.", "Consumer Cyclical"],
    ["7510", "TAKEBISHI CORPORATION", "Consumer Cyclical"],
    ["7512", "Aeon Hokkaido Corporation", "Consumer Cyclical"],
    ["7513", "Kojima Co.,Ltd.", "Consumer Cyclical"],
    ["7516", "KOHNAN SHOJI CO.,LTD.", "Consumer Cyclical"],
    ["7520", "Eco's Co.,Ltd.", "Consumer Cyclical"],
    ["7522", "WATAMI CO.,LTD.", "Consumer Cyclical"],
    ["7525", "RIX CORPORATION", "Consumer Cyclical"],
    ["7527", "SystemSoft Corporation", "Technology"],
    ["7532", "Pan Pacific International Holdings Corporation", "Consumer Cyclical"],
    ["7537", "MARUBUN CORPORATION", "Consumer Cyclical"],
    ["7545", "NISHIMATSUYA CHAIN Co.,Ltd.", "Consumer Cyclical"],
    ["7550", "ZENSHO HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["7552", "HAPPINET CORPORATION", "Consumer Cyclical"],
    ["7554", "KOURAKUEN CORPORATION", "Consumer Cyclical"],
    ["7570", "HASHIMOTO SOGYO HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["7575", "Japan Lifeline Co.,Ltd.", "Consumer Cyclical"],
    ["7581", "SAIZERIYA CO.,LTD.", "Consumer Cyclical"],
    ["7590", "TAKASHO CO.,LTD.", "Consumer Cyclical"],
    ["7593", "VT HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["7595", "ARGO GRAPHICS Inc.", "Technology"],
    ["7596", "UORIKI CO.,LTD.", "Consumer Cyclical"],
    ["7599", "IDOM Inc.", "Consumer Cyclical"],
    ["7600", "Japan Medical Dynamic Marketing,INC.", "Technology"],
    ["7606", "UNITED ARROWS LTD.", "Consumer Cyclical"],
    ["7607", "Shinwa Co.,Ltd.", "Consumer Cyclical"],
    ["7609", "Daitron Co.,Ltd.", "Consumer Cyclical"],
    ["7611", "HIDAY HIDAKA Corp.", "Consumer Cyclical"],
    ["7613", "SIIX CORPORATION", "Consumer Cyclical"],
    ["7616", "COLOWIDE CO.,LTD.", "Consumer Cyclical"],
    ["7628", "OHASHI TECHNICA INC.", "Consumer Cyclical"],
    ["7630", "ICHIBANYA CO.,LTD.", "Consumer Cyclical"],
    ["7637", "Hakudo Co.,Ltd.", "Consumer Cyclical"],
    ["7649", "SUGI HOLDINGS Co.,LTD.", "Consumer Cyclical"],
    ["7679", "YAKUODO HOLDINGS Co.,Ltd.", "Consumer Cyclical"],
    ["7683", "WA,Inc.", "Consumer Cyclical"],
    ["7701", "Shimadzu Corporation", "Technology"],
    ["7702", "JMS CO.,LTD.", "Technology"],
    ["7715", "NAGANO KEIKI CO.,LTD.", "Technology"],
    ["7717", "V Technology Co.,Ltd.", "Technology"],
    ["7721", "TOKYO KEIKI INC.", "Technology"],
    ["7723", "Aichi Tokei Denki Co.,Ltd.", "Technology"],
    ["7725", "INTER ACTION Corporation", "Technology"],
    ["7729", "TOKYO SEIMITSU CO.,LTD.", "Technology"],
    ["7730", "MANI,INC.", "Technology"],
    ["7731", "NIKON CORPORATION", "Technology"],
    ["7733", "OLYMPUS CORPORATION", "Technology"],
    ["7734", "RIKEN KEIKI CO.,LTD.", "Technology"],
    ["7735", "SCREEN Holdings Co.,Ltd.", "Technology"],
    ["7740", "Tamron Co.,Ltd.", "Technology"],
    ["7741", "HOYA CORPORATION", "Technology"],
    ["7744", "Noritsu Koki Co.,Ltd.", "Technology"],
    ["7745", "A&D HOLON Holdings Company,Limited", "Technology"],
    ["7747", "ASAHI INTECC CO.,LTD.", "Technology"],
    ["7751", "CANON INC.", "Technology"],
    ["7752", "RICOH COMPANY,LTD.", "Technology"],
    ["7762", "Citizen Watch Co.,Ltd.", "Technology"],
    ["7780", "Menicon Co.,Ltd.", "Technology"],
    ["7818", "TRANSACTION CO.,Ltd.", "Consumer Cyclical"],
    ["7820", "NIHON FLUSH CO.,LTD.", "Consumer Cyclical"],
    ["7821", "MAEDA KOSEN CO.,LTD.", "Consumer Cyclical"],
    ["7823", "ARTNATURE INC.", "Consumer Cyclical"],
    ["7826", "FURUYA METAL CO.,LTD.", "Consumer Cyclical"],
    ["7832", "Bandai Namco Holdings Inc.", "Consumer Cyclical"],
    ["7839", "SHOEI CO.,LTD.", "Consumer Cyclical"],
    ["7840", "FRANCE BED HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["7844", "Marvelous Inc.", "Technology"],
    ["7846", "PILOT CORPORATION", "Consumer Cyclical"],
    ["7856", "HAGIHARA INDUSTRIES INC.", "Consumer Cyclical"],
    ["7860", "Avex Inc.", "Technology"],
    ["7864", "FUJI SEAL INTERNATIONAL,INC.", "Consumer Cyclical"],
    ["7867", "TOMY COMPANY,LTD.", "Consumer Cyclical"],
    ["7868", "KOSAIDO Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["7874", "LEC,INC.", "Basic Materials"],
    ["7888", "SANKO GOSEI LTD.", "Basic Materials"],
    ["7893", "PRONEXUS INC.", "Consumer Cyclical"],
    ["7911", "TOPPAN Holdings Inc.", "Consumer Cyclical"],
    ["7912", "Dai Nippon Printing Co.,Ltd.", "Consumer Cyclical"],
    ["7914", "Kyodo Printing Co.,Ltd.", "Consumer Cyclical"],
    ["7915", "Nissha Co.,Ltd.", "Consumer Cyclical"],
    ["7917", "ZACROS Corporation", "Basic Materials"],
    ["7921", "TAKARA & COMPANY LTD.", "Consumer Cyclical"],
    ["7925", "MAEZAWA KASEI INDUSTRIES CO.,LTD.", "Basic Materials"],
    ["7931", "MIRAI INDUSTRY CO.,LTD.", "Basic Materials"],
    ["7936", "ASICS Corporation", "Consumer Cyclical"],
    ["7937", "TSUTSUMI JEWELRY CO.,LTD.", "Consumer Cyclical"],
    ["7942", "JSP Corporation", "Basic Materials"],
    ["7943", "NICHIHA CORPORATION", "Basic Materials"],
    ["7944", "Roland Corporation", "Consumer Cyclical"],
    ["7947", "FP CORPORATION", "Basic Materials"],
    ["7949", "KOMATSU WALL INDUSTRY CO.,LTD.", "Consumer Cyclical"],
    ["7951", "YAMAHA CORPORATION", "Consumer Cyclical"],
    ["7952", "Kawai Musical Instruments Manufacturing Co.,Ltd.", "Consumer Cyclical"],
    ["7955", "Cleanup Corporation", "Consumer Cyclical"],
    ["7956", "PIGEON CORPORATION", "Consumer Cyclical"],
    ["7962", "KING JIM CO.,LTD.", "Consumer Cyclical"],
    ["7965", "Zojirushi Corporation", "Technology"],
    ["7966", "LINTEC Corporation", "Consumer Cyclical"],
    ["7970", "Shin-Etsu Polymer Co.,Ltd.", "Basic Materials"],
    ["7972", "ITOKI CORPORATION", "Consumer Cyclical"],
    ["7974", "Nintendo Co.,Ltd.", "Consumer Cyclical"],
    ["7976", "MITSUBISHI PENCIL COMPANY,LIMITED", "Consumer Cyclical"],
    ["7979", "SHOFU INC.", "Technology"],
    ["7981", "TAKARA STANDARD CO.,LTD.", "Consumer Cyclical"],
    ["7984", "KOKUYO CO.,LTD.", "Consumer Cyclical"],
    ["7987", "NAKABAYASHI CO.,LTD.", "Consumer Cyclical"],
    ["7988", "NIFCO INC.", "Basic Materials"],
    ["7989", "TACHIKAWA CORPORATION", "Industrials"],
    ["7990", "GLOBERIDE,Inc.", "Consumer Cyclical"],
    ["7994", "OKAMURA CORPORATION", "Consumer Cyclical"],
    ["7995", "VALQUA,LTD.", "Basic Materials"],
    ["8001", "ITOCHU Corporation", "Consumer Cyclical"],
    ["8002", "Marubeni Corporation", "Consumer Cyclical"],
    ["8005", "Scroll Corporation", "Consumer Cyclical"],
    ["8008", "YONDOSHI HOLDINGS INC.", "Consumer Cyclical"],
    ["8011", "SANYO SHOKAI LTD.", "Consumer Cyclical"],
    ["8012", "NAGASE & CO.,LTD.", "Consumer Cyclical"],
    ["8014", "CHORI CO.,LTD.", "Consumer Cyclical"],
    ["8015", "TOYOTA TSUSHO CORPORATION", "Consumer Cyclical"],
    ["8016", "ONWARD HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["8018", "SANKYO SEIKO CO.,LTD.", "Consumer Cyclical"],
    ["8020", "KANEMATSU CORPORATION", "Consumer Cyclical"],
    ["8022", "Mizuno Corporation", "Consumer Cyclical"],
    ["8029", "LOOK HOLDINGS INCORPORATED", "Consumer Cyclical"],
    ["8031", "MITSUI & CO.,LTD.", "Consumer Cyclical"],
    ["8032", "JAPAN PULP AND PAPER COMPANY LIMITED", "Consumer Cyclical"],
    ["8035", "Tokyo Electron Limited", "Technology"],
    ["8037", "KAMEI CORPORATION", "Consumer Cyclical"],
    ["8043", "Starzen Company Limited", "Consumer Cyclical"],
    ["8050", "SEIKO GROUP CORPORATION", "Technology"],
    ["8051", "YAMAZEN CORPORATION", "Consumer Cyclical"],
    ["8052", "TSUBAKIMOTO KOGYO CO.,LTD.", "Consumer Cyclical"],
    ["8053", "SUMITOMO CORPORATION (SUMITOMO SHOJI KAISHA,LTD.)", "Consumer Cyclical"],
    ["8056", "BIPROGY Inc.", "Technology"],
    ["8057", "UCHIDA YOKO CO.,LTD.", "Consumer Cyclical"],
    ["8058", "Mitsubishi Corporation", "Consumer Cyclical"],
    ["8059", "DAIICHI JITSUGYO CO.,LTD.", "Consumer Cyclical"],
    ["8060", "Canon Marketing Japan Inc.", "Consumer Cyclical"],
    ["8061", "SEIKA CORPORATION", "Consumer Cyclical"],
    ["8065", "SATO SHO-JI CORPORATION", "Consumer Cyclical"],
    ["8070", "TOKYO SANGYO CO.,LTD.", "Consumer Cyclical"],
    ["8074", "YUASA CO.,LTD.", "Consumer Cyclical"],
    ["8075", "Shinsho Corporation", "Consumer Cyclical"],
    ["8078", "HANWA CO.,LTD.", "Consumer Cyclical"],
    ["8079", "SHOEI FOODS CORPORATION", "Consumer Cyclical"],
    ["8081", "KANADEN CORPORATION", "Consumer Cyclical"],
    ["8084", "RYODEN CORPORATION", "Consumer Cyclical"],
    ["8086", "NIPRO CORPORATION", "Technology"],
    ["8088", "IWATANI  CORPORATION", "Consumer Cyclical"],
    ["8093", "Kyokuto Boeki Kaisha,Limited", "Consumer Cyclical"],
    ["8095", "Astena Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["8097", "SAN-AI OBBLI CO.,LTD.", "Consumer Cyclical"],
    ["8098", "Inabata & Co.,Ltd.", "Consumer Cyclical"],
    ["8101", "GSI Creos Corporation", "Consumer Cyclical"],
    ["8103", "Meiwa Corporation", "Consumer Cyclical"],
    ["8111", "Goldwin Inc.", "Consumer Cyclical"],
    ["8113", "UNICHARM CORPORATION", "Basic Materials"],
    ["8125", "Wakita & Co.,LTD.", "Consumer Cyclical"],
    ["8129", "TOHO HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["8130", "Sangetsu Corporation", "Consumer Cyclical"],
    ["8131", "Mitsuuroko Group Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["8132", "SINANEN HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["8133", "ITOCHU ENEX CO.,LTD.", "Consumer Cyclical"],
    ["8136", "Sanrio Company,Ltd.", "Consumer Cyclical"],
    ["8137", "SUN-WA TECHNOS CORPORATION", "Consumer Cyclical"],
    ["8141", "Shinko Shoji Co.,Ltd.", "Consumer Cyclical"],
    ["8142", "TOHO Co.,Ltd.", "Consumer Cyclical"],
    ["8150", "SANSHIN ELECTRONICS CO.,LTD.", "Consumer Cyclical"],
    ["8151", "TOYO Corporation", "Consumer Cyclical"],
    ["8153", "MOS FOOD SERVICES,INC.", "Consumer Cyclical"],
    ["8154", "KAGA ELECTRONICS CO.,LTD.", "Consumer Cyclical"],
    ["8157", "TSUZUKI DENKI CO.,LTD.", "Technology"],
    ["8158", "SODA NIKKA CO.,LTD.", "Consumer Cyclical"],
    ["8159", "TACHIBANA ELETECH CO.,LTD.", "Consumer Cyclical"],
    ["8160", "KISOJI CO.,LTD.", "Consumer Cyclical"],
    ["8163", "SRS HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["8165", "SENSHUKAI CO.,LTD.", "Consumer Cyclical"],
    ["8167", "RETAIL PARTNERS CO.,LTD.", "Consumer Cyclical"],
    ["8173", "Joshin Corporation", "Consumer Cyclical"],
    ["8174", "NIPPON GAS CO.,LTD.", "Consumer Cyclical"],
    ["8179", "ROYAL HOLDINGS Co., Ltd.", "Consumer Cyclical"],
    ["8185", "CHIYODA CO.,LTD.", "Consumer Cyclical"],
    ["8194", "LIFE CORPORATION", "Consumer Cyclical"],
    ["8200", "RINGER HUT CO.,LTD.", "Consumer Cyclical"],
    ["8203", "MrMax Holdings Ltd.", "Consumer Cyclical"],
    ["8214", "AOKI Holdings Inc.", "Consumer Cyclical"],
    ["8217", "OKUWA CO.,LTD.", "Consumer Cyclical"],
    ["8218", "KOMERI CO.,LTD.", "Consumer Cyclical"],
    ["8219", "AOYAMA TRADING Co.,Ltd.", "Consumer Cyclical"],
    ["8227", "SHIMAMURA Co.,Ltd.", "Consumer Cyclical"],
    ["8233", "Takashimaya Company,Limited", "Consumer Cyclical"],
    ["8237", "MATSUYA CO.,LTD.", "Consumer Cyclical"],
    ["8242", "H2O RETAILING CORPORATION", "Consumer Cyclical"],
    ["8244", "Kintetsu Department Store CO.,Ltd.", "Consumer Cyclical"],
    ["8252", "MARUI GROUP CO.,LTD.", "Consumer Cyclical"],
    ["8253", "Credit Saison Co.,Ltd.", "Industrials"],
    ["8255", "Axial Retailing Inc.", "Consumer Cyclical"],
    ["8267", "AEON CO.,LTD.", "Consumer Cyclical"],
    ["8273", "IZUMI CO.,LTD.", "Consumer Cyclical"],
    ["8275", "FORVAL CORPORATION", "Consumer Cyclical"],
    ["8276", "HEIWADO CO.,LTD.", "Consumer Cyclical"],
    ["8278", "FUJI CO.,LTD.", "Consumer Cyclical"],
    ["8281", "XEBIO holdings CO.,LTD.", "Consumer Cyclical"],
    ["8282", "K'S HOLDINGS CORPORATION", "Consumer Cyclical"],
    ["8283", "PALTAC CORPORATION", "Consumer Cyclical"],
    ["8285", "MITANI SANGYO CO.,LTD.", "Consumer Cyclical"],
    ["8303", "SBI Shinsei Bank,Limited", "Financial Services"],
    ["8304", "Aozora Bank,Ltd.", "Financial Services"],
    ["8306", "Mitsubishi UFJ Financial Group,Inc.", "Financial Services"],
    ["8308", "Resona Holdings, Inc.", "Financial Services"],
    ["8309", "Sumitomo Mitsui Trust Group,Inc.", "Financial Services"],
    ["8316", "Sumitomo Mitsui Financial Group,Inc.", "Financial Services"],
    ["8331", "The Chiba Bank,Ltd.", "Financial Services"],
    ["8334", "The Gunma Bank,Ltd.", "Financial Services"],
    ["8336", "The Musashino Bank,Ltd.", "Financial Services"],
    ["8337", "The Chiba Kogyo Bank,Ltd.", "Financial Services"],
    ["8338", "Tsukuba Bank,Ltd.", "Financial Services"],
    ["8341", "The 77 Bank,Ltd.", "Financial Services"],
    ["8343", "THE AKITA BANK,LTD.", "Financial Services"],
    ["8344", "The Yamagata Bank,Ltd.", "Financial Services"],
    ["8345", "The Bank of Iwate,Ltd.", "Financial Services"],
    ["8346", "The Toho Bank,Ltd.", "Financial Services"],
    ["8354", "Fukuoka Financial Group,Inc.", "Financial Services"],
    ["8358", "Suruga Bank Ltd.", "Financial Services"],
    ["8359", "Hachijuni Nagano Bank,Ltd.", "Financial Services"],
    ["8360", "The Yamanashi Chuo Bank,Ltd.", "Financial Services"],
    ["8361", "The Ogaki Kyoritsu Bank,Ltd.", "Financial Services"],
    ["8362", "The Fukui Bank,Ltd.", "Financial Services"],
    ["8364", "THE SHIMIZU BANK,LTD.", "Financial Services"],
    ["8366", "THE SHIGA BANK,LTD.", "Financial Services"],
    ["8367", "The Nanto Bank,Ltd.", "Financial Services"],
    ["8368", "The Hyakugo Bank,Ltd.", "Financial Services"],
    ["8370", "The Kiyo Bank,Ltd.", "Financial Services"],
    ["8377", "Hokuhoku Financial Group, Inc.", "Financial Services"],
    ["8381", "The San-in Godo Bank,Ltd.", "Financial Services"],
    ["8386", "The Hyakujushi Bank,Ltd.", "Financial Services"],
    ["8387", "The Shikoku Bank, Ltd.", "Financial Services"],
    ["8388", "The Awa Bank,Ltd.", "Financial Services"],
    ["8392", "THE OITA BANK,LTD.", "Financial Services"],
    ["8393", "The Miyazaki Bank,Ltd.", "Financial Services"],
    ["8395", "THE BANK OF SAGA LTD.", "Financial Services"],
    ["8399", "Bank of The Ryukyus,Limited", "Financial Services"],
    ["8410", "Seven Bank,Ltd.", "Financial Services"],
    ["8411", "Mizuho Financial Group,Inc.", "Financial Services"],
    ["8418", "Yamaguchi Financial Group,Inc.", "Financial Services"],
    ["8424", "Fuyo General Lease Co.,Ltd.", "Industrials"],
    ["8425", "Mizuho Leasing Company,Limited", "Industrials"],
    ["8439", "Tokyo Century Corporation", "Industrials"],
    ["8473", "SBI Holdings,Inc.", "Financial Services"],
    ["8511", "Japan Securities Finance Co.,Ltd.", "Industrials"],
    ["8522", "The Bank of Nagoya,Ltd.", "Financial Services"],
    ["8524", "North Pacific Bank,Ltd.", "Financial Services"],
    ["8541", "The Ehime Bank,Ltd.", "Financial Services"],
    ["8544", "The Keiyo Bank,Ltd.", "Financial Services"],
    ["8550", "THE TOCHIGI BANK,LTD.", "Financial Services"],
    ["8551", "The Kita-Nippon Bank,Ltd.", "Financial Services"],
    ["8558", "THE TOWA BANK,LTD.", "Financial Services"],
    ["8566", "RICOH LEASING COMPANY,LTD.", "Industrials"],
    ["8570", "AEON Financial Service Co.,Ltd.", "Industrials"],
    ["8572", "ACOM CO.,LTD.", "Industrials"],
    ["8584", "JACCS CO.,LTD.", "Industrials"],
    ["8585", "Orient Corporation", "Industrials"],
    ["8591", "ORIX CORPORATION", "Industrials"],
    ["8593", "Mitsubishi HC Capital Inc.", "Industrials"],
    ["8595", "JAFCO Group Co.,Ltd.", "Financial Services"],
    ["8600", "TOMONY Holdings,Inc.", "Financial Services"],
    ["8601", "Daiwa Securities Group Inc.", "Financial Services"],
    ["8604", "Nomura Holdings, Inc.", "Financial Services"],
    ["8609", "OKASAN SECURITIES GROUP INC.", "Financial Services"],
    ["8613", "Marusan Securities Co.,Ltd.", "Financial Services"],
    ["8614", "TOYO SECURITIES CO.,LTD.", "Financial Services"],
    ["8616", "Tokai Tokyo Financial Holdings,Inc.", "Financial Services"],
    ["8622", "Mito Securities Co.,Ltd.", "Financial Services"],
    ["8624", "Ichiyoshi Securities Co.,Ltd.", "Financial Services"],
    ["8628", "MATSUI SECURITIES CO.,LTD.", "Financial Services"],
    ["8630", "Sompo Holdings,Inc.", "Financial Services"],
    ["8697", "Japan Exchange Group,Inc.", "Industrials"],
    ["8698", "Monex Group,Inc.", "Financial Services"],
    ["8706", "KYOKUTO SECURITIES CO.,LTD.", "Financial Services"],
    ["8707", "IwaiCosmo Holdings,Inc.", "Financial Services"],
    ["8708", "AIZAWA SECURITIES GROUP CO.,LTD.", "Financial Services"],
    ["8713", "FIDEA Holdings Co.Ltd.", "Financial Services"],
    ["8714", "Senshu Ikeda Holdings,Inc.", "Financial Services"],
    ["8715", "Anicom Holdings,Inc.", "Financial Services"],
    ["8725", "MS&AD Insurance Group Holdings,Inc.", "Financial Services"],
    ["8729", "Sony Financial Group Inc.", "Financial Services"],
    ["8739", "SPARX Group Co.,Ltd.", "Financial Services"],
    ["8750", "Daiichi Life Group,Inc.", "Financial Services"],
    ["8766", "Tokio Marine Holdings,Inc.", "Financial Services"],
    ["8771", "eGuarantee,Inc.", "Industrials"],
    ["8793", "NEC Capital Solutions Limited", "Industrials"],
    ["8795", "T&D Holdings, Inc.", "Financial Services"],
    ["8798", "Advance Create Co.,Ltd.", "Financial Services"],
    ["8801", "Mitsui Fudosan Co.,Ltd.", "Real Estate"],
    ["8802", "Mitsubishi Estate Company,Limited", "Real Estate"],
    ["8803", "HEIWA REAL ESTATE CO.,LTD.", "Real Estate"],
    ["8804", "Tokyo Tatemono Co.,Ltd.", "Real Estate"],
    ["8818", "Keihanshin Building Co.,Ltd.", "Real Estate"],
    ["8830", "Sumitomo Realty & Development Co.,Ltd.", "Real Estate"],
    ["8841", "TOC Co.,Ltd.", "Real Estate"],
    ["8848", "LEOPALACE21 CORPORATION", "Real Estate"],
    ["8850", "STARTS CORPORATION INC.", "Real Estate"],
    ["8860", "FUJI CORPORATION LIMITED", "Real Estate"],
    ["8864", "AIRPORT FACILITIES Co.,LTD.", "Real Estate"],
    ["8869", "Meiwa Estate Company Limited", "Real Estate"],
    ["8871", "GOLDCREST Co.,Ltd.", "Real Estate"],
    ["8876", "Relo Group,Inc.", "Industrials"],
    ["8877", "ESLEAD CORPORATION", "Real Estate"],
    ["8881", "NISSHIN GROUP HOLDINGS Company,Limited", "Real Estate"],
    ["8892", "ES-CON JAPAN Ltd.", "Real Estate"],
    ["8897", "MIRARTH HOLDINGS,Inc.", "Real Estate"],
    ["8918", "LAND Co.,Ltd.", "Real Estate"],
    ["8919", "KATITAS CO.,LTD", "Real Estate"],
    ["8920", "TOSHO CO.,LTD.", "Industrials"],
    ["8923", "TOSEI CORPORATION", "Real Estate"],
    ["8934", "Sun Frontier Fudousan Co.,Ltd.", "Real Estate"],
    ["8935", "FJ NEXT HOLDINGS CO.,LTD.", "Real Estate"],
    ["8999", "Grandy House Corporation", "Real Estate"],
    ["9001", "TOBU RAILWAY CO.,LTD.", "Industrials"],
    ["9003", "Sotetsu Holdings,Inc.", "Industrials"],
    ["9005", "TOKYU CORPORATION", "Industrials"],
    ["9006", "Keikyu Corporation", "Industrials"],
    ["9007", "Odakyu Electric Railway Co.,Ltd.", "Industrials"],
    ["9008", "Keio Corporation", "Industrials"],
    ["9009", "Keisei Electric Railway Co.,Ltd.", "Industrials"],
    ["9010", "FUJI KYUKO CO.,LTD.", "Industrials"],
    ["9020", "East Japan Railway Company", "Industrials"],
    ["9021", "West Japan Railway Company", "Industrials"],
    ["9022", "Central Japan Railway Company", "Industrials"],
    ["9023", "Tokyo Metro Co.,Ltd.", "Industrials"],
    ["9024", "SEIBU HOLDINGS INC.", "Industrials"],
    ["9025", "Konoike Transport Co.,Ltd.", "Industrials"],
    ["9031", "Nishi-Nippon Railroad Co.,Ltd.", "Industrials"],
    ["9037", "HAMAKYOREX CO.,LTD.", "Industrials"],
    ["9039", "Sakai Moving Service Co.,Ltd.", "Industrials"],
    ["9041", "Kintetsu Group Holdings Co.,Ltd.", "Industrials"],
    ["9042", "Hankyu Hanshin Holdings,Inc.", "Industrials"],
    ["9044", "NANKAI Co.,Ltd.", "Industrials"],
    ["9045", "Keihan Holdings Co.,Ltd.", "Industrials"],
    ["9046", "Kobe Electric Railway Co.,Ltd.", "Industrials"],
    ["9048", "Nagoya Railroad Co., Ltd.", "Industrials"],
    ["9052", "Sanyo Electric Railway Co.,Ltd.", "Industrials"],
    ["9064", "YAMATO HOLDINGS CO.,LTD.", "Industrials"],
    ["9065", "SANKYU INC.", "Industrials"],
    ["9068", "Maruzen Showa Unyu Co.,Ltd.", "Industrials"],
    ["9069", "SENKO Group Holdings Co.,Ltd.", "Industrials"],
    ["9072", "NIKKON Holdings Co.,Ltd.", "Industrials"],
    ["9075", "FUKUYAMA TRANSPORTING CO.,LTD.", "Industrials"],
    ["9076", "SEINO HOLDINGS CO.,LTD.", "Industrials"],
    ["9081", "Kanagawa Chuo Kotsu Co.,Ltd.", "Industrials"],
    ["9090", "AZ-COM MARUWA Holdings Inc.", "Industrials"],
    ["9101", "Nippon Yusen Kabushiki Kaisha", "Industrials"],
    ["9104", "Mitsui O.S.K.Lines,Ltd.", "Industrials"],
    ["9107", "Kawasaki Kisen Kaisha,Ltd.", "Industrials"],
    ["9110", "NS United Kaiun Kaisha,Ltd.", "Industrials"],
    ["9119", "IINO KAIUN KAISHA,LTD.", "Industrials"],
    ["9142", "Kyushu Railway Company", "Industrials"],
    ["9143", "SG HOLDINGS CO.,LTD.", "Industrials"],
    ["9147", "NIPPON EXPRESS HOLDINGS,INC.", "Industrials"],
    ["9201", "Japan Airlines Co.,Ltd.", "Industrials"],
    ["9202", "ANA HOLDINGS INC.", "Industrials"],
    ["9216", "Bewith,Inc.", "Industrials"],
    ["9229", "SUNWELS Co.,Ltd.", "Industrials"],
    ["9247", "TRE HOLDINGS CORPORATION", "Industrials"],
    ["9248", "People, Dreams & Technologies Group Co.,Ltd.", "Industrials"],
    ["9262", "SILVER LIFE CO.,LTD.", "Consumer Cyclical"],
    ["9267", "Genky DrugStores Co.,Ltd.", "Consumer Cyclical"],
    ["9273", "KOA SHOJI HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["9274", "KPP GROUP HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["9278", "BOOKOFF GROUP HOLDINGS LIMITED", "Consumer Cyclical"],
    ["9279", "GIFT HOLDINGS INC.", "Consumer Cyclical"],
    ["9301", "Mitsubishi Logistics Corporation", "Industrials"],
    ["9302", "MITSUI-SOKO HOLDINGS Co.,Ltd.", "Industrials"],
    ["9303", "The Sumitomo Warehouse Co.,Ltd.", "Industrials"],
    ["9304", "Shibusawa Logistics Corporation", "Industrials"],
    ["9305", "Yamatane Corporation", "Consumer Cyclical"],
    ["9308", "Inui Global Logistics Co.,Ltd.", "Industrials"],
    ["9310", "Japan Transcity Corporation", "Industrials"],
    ["9319", "Chuo Warehouse Co.,Ltd.", "Industrials"],
    ["9324", "Yasuda Logistics Corporation", "Industrials"],
    ["9332", "NISSO HOLDINGS Co.,Ltd.", "Industrials"],
    ["9336", "Daiei Kankyo Co.,Ltd.", "Industrials"],
    ["9341", "GENOVA,Inc.", "Industrials"],
    ["9347", "NIPPON KANZAI Holdings Co.,Ltd.", "Industrials"],
    ["9364", "Kamigumi Co.,Ltd.", "Industrials"],
    ["9369", "K.R.S.Corporation", "Industrials"],
    ["9381", "AIT CORPORATION", "Industrials"],
    ["9401", "TBS HOLDINGS,INC.", "Technology"],
    ["9404", "Nippon Television Holdings,Inc.", "Technology"],
    ["9405", "ASAHI BROADCASTING GROUP HOLDINGS CORPORATION", "Technology"],
    ["9409", "TV Asahi Holdings Corporation", "Technology"],
    ["9412", "SKY Perfect JSAT Corporation", "Technology"],
    ["9413", "TV TOKYO Holdings Corporation", "Technology"],
    ["9416", "VISION INC.", "Technology"],
    ["9418", "U-NEXT HOLDINGS Co.,Ltd.", "Technology"],
    ["9424", "Japan Communications Inc.", "Technology"],
    ["9432", "NTT,Inc.", "Technology"],
    ["9433", "KDDI CORPORATION", "Technology"],
    ["9434", "SoftBank Corp.", "Technology"],
    ["9435", "HIKARI TSUSHIN,INC.", "Technology"],
    ["9438", "MTI Ltd.", "Technology"],
    ["9449", "GMO internet group,Inc.", "Technology"],
    ["9450", "Fibergate Inc.", "Technology"],
    ["9468", "KADOKAWA CORPORATION", "Technology"],
    ["9470", "GAKKEN HOLDINGS CO.,LTD.", "Technology"],
    ["9474", "ZENRIN CO.,LTD.", "Technology"],
    ["9501", "Tokyo Electric Power Company Holdings,Incorporated", "Utilities"],
    ["9502", "Chubu Electric Power Company,Incorporated", "Utilities"],
    ["9503", "The Kansai Electric Power Company,Incorporated", "Utilities"],
    ["9504", "The Chugoku Electric Power Company,Incorporated", "Utilities"],
    ["9505", "Hokuriku Electric Power Company", "Utilities"],
    ["9506", "Tohoku Electric Power Company,Incorporated", "Utilities"],
    ["9507", "Shikoku Electric Power Company,Incorporated", "Utilities"],
    ["9508", "Kyushu Electric Power Company,Incorporated", "Utilities"],
    ["9509", "Hokkaido Electric Power Company,Incorporated", "Utilities"],
    ["9511", "The Okinawa Electric Power Company,Incorporated", "Utilities"],
    ["9513", "Electric Power Development Co.,Ltd.", "Utilities"],
    ["9514", "EF-ON INC.", "Utilities"],
    ["9517", "eREX Co.,Ltd.", "Utilities"],
    ["9519", "RENOVA,Inc.", "Utilities"],
    ["9531", "TOKYO GAS CO.,LTD.", "Utilities"],
    ["9532", "OSAKA GAS CO.,LTD.", "Utilities"],
    ["9533", "TOHO GAS CO.,LTD.", "Utilities"],
    ["9534", "HOKKAIDO GAS CO.,LTD.", "Utilities"],
    ["9535", "HIROSHIMA GAS CO.,LTD.", "Utilities"],
    ["9536", "SAIBU GAS HOLDINGS CO.,LTD.", "Utilities"],
    ["9543", "SHIZUOKA GAS CO.,LTD.", "Utilities"],
    ["9551", "METAWATER Co.,Ltd.", "Utilities"],
    ["9552", "Quants Research Institute Holdings,Inc.", "Industrials"],
    ["9601", "Shochiku Co.,Ltd.", "Technology"],
    ["9602", "TOHO CO.,LTD", "Technology"],
    ["9603", "H.I.S.Co.,Ltd.", "Industrials"],
    ["9605", "TOEI COMPANY,LTD.", "Technology"],
    ["9612", "LUCKLAND CO.,LTD.", "Industrials"],
    ["9616", "KYORITSU MAINTENANCE CO.,LTD.", "Industrials"],
    ["9619", "ICHINEN HOLDINGS CO.,LTD.", "Industrials"],
    ["9621", "CTI Engineering Co.,Ltd.", "Industrials"],
    ["9622", "SPACE CO.,LTD.", "Industrials"],
    ["9627", "AIN HOLDINGS INC.", "Consumer Cyclical"],
    ["9628", "SAN HOLDINGS,INC.", "Industrials"],
    ["9629", "PCA CORPORATION", "Technology"],
    ["9632", "Subaru Enterprise Co.,Ltd.", "Industrials"],
    ["9644", "TANABE CONSULTING GROUP CO.,LTD.", "Industrials"],
    ["9658", "BUSINESS BRAIN SHOWA�EOTA INC.", "Technology"],
    ["9663", "NAGAWA CO.,Ltd", "Industrials"],
    ["9672", "TOKYOTOKEIBA CO.,LTD.", "Industrials"],
    ["9678", "KANAMOTO CO.,LTD.", "Industrials"],
    ["9682", "DTS CORPORATION", "Technology"],
    ["9684", "SQUARE ENIX HOLDINGS CO.,LTD.", "Technology"],
    ["9692", "COMPUTER ENGINEERING & CONSULTING LTD.", "Technology"],
    ["9697", "CAPCOM CO.,LTD.", "Technology"],
    ["9699", "NISHIO HOLDINGS CO.,LTD.", "Industrials"],
    ["9702", "ISB CORPORATION", "Technology"],
    ["9706", "Japan Airport Terminal Co.,ltd.", "Real Estate"],
    ["9715", "transcosmos inc.", "Industrials"],
    ["9716", "NOMURA Co.,Ltd.", "Industrials"],
    ["9722", "FUJITA KANKO INC.", "Industrials"],
    ["9726", "KNT-CT Holdings Co.,Ltd.", "Industrials"],
    ["9729", "TOKAI Corp.", "Industrials"],
    ["9735", "SECOM CO.,LTD.", "Industrials"],
    ["9739", "NSW Inc.", "Technology"],
    ["9740", "CENTRAL SECURITY PATROLS CO.,LTD.", "Industrials"],
    ["9742", "INES Corporation", "Technology"],
    ["9743", "TANSEISHA CO.,LTD.", "Industrials"],
    ["9744", "MEITEC Group Holdings Inc.", "Industrials"],
    ["9746", "TKC Corporation", "Technology"],
    ["9755", "OYO Corporation", "Industrials"],
    ["9757", "Funai Soken Holdings Incorporated", "Industrials"],
    ["9759", "NSD CO.,LTD.", "Technology"],
    ["9766", "KONAMI GROUP CORPORATION", "Technology"],
    ["9769", "GAKKYUSHA CO.,LTD.", "Industrials"],
    ["9788", "NAC CO.,LTD.", "Industrials"],
    ["9790", "Fukui Computer Holdings,Inc.", "Technology"],
    ["9793", "Daiseki Co.,Ltd.", "Industrials"],
    ["9795", "STEP CO.,LTD.", "Industrials"],
    ["9824", "SENSHU ELECTRIC CO.,LTD.", "Consumer Cyclical"],
    ["9828", "Genki Global Dining Concepts Corporation", "Consumer Cyclical"],
    ["9830", "TRUSCO NAKAYAMA CORPORATION", "Consumer Cyclical"],
    ["9831", "YAMADA HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["9832", "AUTOBACS SEVEN CO.,LTD.", "Consumer Cyclical"],
    ["9837", "MORITO CO.,LTD.", "Consumer Cyclical"],
    ["9842", "ARCLANDS CORPORATION", "Consumer Cyclical"],
    ["9843", "Nitori Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["9850", "GOURMET KINEYA CO.,LTD.", "Consumer Cyclical"],
    ["9856", "KU HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["9861", "YOSHINOYA HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["9869", "KATO SANGYO CO.,LTD.", "Consumer Cyclical"],
    ["9880", "INNOTECH CORPORATION", "Technology"],
    ["9882", "YELLOW HAT LTD.", "Consumer Cyclical"],
    ["9887", "MATSUYA FOODS HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["9889", "JBCC Holdings Inc.", "Technology"],
    ["9896", "JK Holdings Co.,Ltd.", "Consumer Cyclical"],
    ["9900", "Sagami Holdings Corporation", "Consumer Cyclical"],
    ["9902", "NICHIDEN Corporation", "Consumer Cyclical"],
    ["9928", "MIROKU JYOHO SERVICE CO.,LTD.", "Technology"],
    ["9932", "SUGIMOTO & CO.,LTD.", "Consumer Cyclical"],
    ["9934", "INABA DENKISANGYO CO.,LTD.", "Consumer Cyclical"],
    ["9936", "OHSHO FOOD SERVICE CORP.", "Consumer Cyclical"],
    ["9946", "MINISTOP CO.,LTD.", "Consumer Cyclical"],
    ["9948", "ARCS COMPANY,LIMITED", "Consumer Cyclical"],
    ["9956", "VALOR HOLDINGS CO.,LTD.", "Consumer Cyclical"],
    ["9960", "TOTECH CORPORATION", "Consumer Cyclical"],
    ["9962", "MISUMI Group Inc.", "Consumer Cyclical"],
    ["9974", "Belc CO.,LTD.", "Consumer Cyclical"],
    ["9979", "DAISYO CORPORATION", "Consumer Cyclical"],
    ["9983", "FAST RETAILING CO.,LTD.", "Consumer Cyclical"],
    ["9984", "SoftBank Group Corp.", "Technology"],
    ["9987", "SUZUKEN CO.,LTD.", "Consumer Cyclical"],
    ["9989", "SUNDRUG CO.,LTD.", "Consumer Cyclical"],
    ["9990", "SAC'S BAR HOLDINGS INC.", "Consumer Cyclical"],
    ["9991", "GECOSS CORPORATION", "Consumer Cyclical"],
    ["9997", "BELLUNA CO.,LTD.", "Consumer Cyclical"],
]

def _parse_eodhd_item(item: dict) -> Optional[dict]:
    """Extract code + name + type from an EODHD exchange-symbol-list record."""
    code = (item.get("Code") or item.get("code") or "").strip()
    name = (item.get("Name") or item.get("name") or "").strip()
    itype = (item.get("Type") or item.get("type") or "").strip().lower()
    if not code or not name:
        return None
    # Keep only common stocks (exclude ETFs, warrants, preferred, etc.)
    if itype and itype not in ("common stock", "stock", "equity", ""):
        return None
    return {"code": code, "name": name, "sector": ""}


def _fetch_from_eodhd(api_key: str) -> List[dict]:
    """Fetch full TSE symbol list from EODHD. Returns list of {code, name, sector}."""
    try:
        import requests as _r
    except ImportError:
        return []

    base = "https://eodhistoricaldata.com/api/exchange-symbol-list"
    for exch in ("T", "TSE", "JPX"):
        try:
            resp = _r.get(
                f"{base}/{exch}",
                params={"api_token": api_key, "fmt": "json"},
                timeout=60,
            )
            if resp.status_code == 200:
                raw = resp.json()
                if isinstance(raw, list) and raw:
                    out = []
                    for item in raw:
                        parsed = _parse_eodhd_item(item)
                        if parsed:
                            out.append(parsed)
                    logger.info("Fetched %d Japan tickers from EODHD (exchange=%s)",
                                len(out), exch)
                    return out
        except Exception as e:
            logger.warning("EODHD Japan fetch failed (exchange=%s): %s", exch, e)
    return []


def _load_cache() -> Optional[List[dict]]:
    if not _CACHE.exists():
        return None
    try:
        age = time.time() - _CACHE.stat().st_mtime
        if age > _CACHE_TTL:
            return None
        with open(_CACHE, encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, list) and data else None
    except Exception:
        return None


def _save_cache(data: List[dict]) -> None:
    _CACHE.parent.mkdir(exist_ok=True)
    try:
        with open(_CACHE, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
    except Exception as e:
        logger.warning("Japan tickers cache save failed: %s", e)


def _seed_list() -> List[dict]:
    """Return the built-in seed list as {code, name, sector} dicts."""
    return [{"code": c, "name": n, "sector": s} for c, n, s in _SEED]


# ── Public API ─────────────────────────────────────────────────────────────────

def get_japan_tickers(api_key: str = "") -> List[dict]:
    """
    Return the full list of TSE-listed companies as [{code, name, sector}].
    Uses a 7-day local cache. Falls back to seed list if EODHD unavailable.
    """
    cached = _load_cache()
    if cached:
        return cached

    if api_key:
        fetched = _fetch_from_eodhd(api_key)
        if fetched:
            _save_cache(fetched)
            return fetched

    return _seed_list()


def search_japan(
    query: str,
    api_key: str = "",
    max_results: int = 5,
) -> List[tuple[str, str]]:
    """
    Search TSE tickers by ticker code or company name.

    Args:
        query:       User search query (partial ticker or name).
        api_key:     EODHD API key for cache population.
        max_results: Max suggestions to return.

    Returns:
        List of (display_label, yf_ticker) tuples.
        yf_ticker is in Yahoo Finance format: "7203.T"
    """
    q = (query or "").strip().lower()
    if q.endswith(".t"):
        q = q[:-2]
    if not q or len(q) < 2:
        return []

    tickers = get_japan_tickers(api_key)
    results: List[tuple[str, str]] = []

    for item in tickers:
        code = item.get("code", "").strip()
        name = item.get("name", "").strip()
        if not code:
            continue
        if q in code.lower() or q in name.lower():
            yf_ticker = f"{code}.T"
            sector = item.get("sector", "")
            label = f"{yf_ticker:<10}  {name[:50]}"
            if sector:
                label += f"  ({sector})"
            label += "  · TSE"
            results.append((label, yf_ticker))
        if len(results) >= max_results:
            break

    return results


def refresh_cache(api_key: str) -> int:
    """Force-refresh the Japan tickers cache from EODHD. Returns count fetched."""
    fetched = _fetch_from_eodhd(api_key)
    if fetched:
        _save_cache(fetched)
        return len(fetched)
    return 0
